
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model AdminUser
 * 
 */
export type AdminUser = Prisma.AdminUserModel
/**
 * Model Category
 * 
 */
export type Category = Prisma.CategoryModel
/**
 * Model Product
 * 
 */
export type Product = Prisma.ProductModel
/**
 * Model ProductVariant
 * 
 */
export type ProductVariant = Prisma.ProductVariantModel
/**
 * Model Supplier
 * 
 */
export type Supplier = Prisma.SupplierModel
/**
 * Model SupplierProduct
 * 
 */
export type SupplierProduct = Prisma.SupplierProductModel
/**
 * Model SalesOrder
 * 
 */
export type SalesOrder = Prisma.SalesOrderModel
/**
 * Model SalesOrderItem
 * 
 */
export type SalesOrderItem = Prisma.SalesOrderItemModel
/**
 * Model InventoryLedger
 * 
 */
export type InventoryLedger = Prisma.InventoryLedgerModel
/**
 * Model Customer
 * 
 */
export type Customer = Prisma.CustomerModel
/**
 * Model CustomerChannelIdentity
 * 
 */
export type CustomerChannelIdentity = Prisma.CustomerChannelIdentityModel
/**
 * Model Procurement
 * 
 */
export type Procurement = Prisma.ProcurementModel
/**
 * Model ProcurementItem
 * 
 */
export type ProcurementItem = Prisma.ProcurementItemModel
