
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Channel = {
  WEB: 'WEB',
  FACEBOOK_POST: 'FACEBOOK_POST',
  FACEBOOK_MARKETPLACE: 'FACEBOOK_MARKETPLACE',
  PHYSICAL: 'PHYSICAL'
} as const

export type Channel = (typeof Channel)[keyof typeof Channel]


export const PaymentMethod = {
  CASH: 'CASH',
  GCASH: 'GCASH',
  MAYA: 'MAYA',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CARD_ONLINE: 'CARD_ONLINE',
  CARD_OTC: 'CARD_OTC'
} as const

export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod]


export const ProcurementStatus = {
  PENDING: 'PENDING',
  ORDERED: 'ORDERED',
  RECEIVED: 'RECEIVED',
  CANCELLED: 'CANCELLED'
} as const

export type ProcurementStatus = (typeof ProcurementStatus)[keyof typeof ProcurementStatus]


export const AdminRole = {
  ADMIN: 'ADMIN'
} as const

export type AdminRole = (typeof AdminRole)[keyof typeof AdminRole]
