
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AccountPayable` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AccountPayable
 * 
 */
export type AccountPayableModel = runtime.Types.Result.DefaultSelection<Prisma.$AccountPayablePayload>

export type AggregateAccountPayable = {
  _count: AccountPayableCountAggregateOutputType | null
  _avg: AccountPayableAvgAggregateOutputType | null
  _sum: AccountPayableSumAggregateOutputType | null
  _min: AccountPayableMinAggregateOutputType | null
  _max: AccountPayableMaxAggregateOutputType | null
}

export type AccountPayableAvgAggregateOutputType = {
  amount: runtime.Decimal | null
  paidAmount: runtime.Decimal | null
}

export type AccountPayableSumAggregateOutputType = {
  amount: runtime.Decimal | null
  paidAmount: runtime.Decimal | null
}

export type AccountPayableMinAggregateOutputType = {
  id: string | null
  supplierId: string | null
  procurementId: string | null
  amount: runtime.Decimal | null
  paidAmount: runtime.Decimal | null
  dueDate: Date | null
  status: string | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AccountPayableMaxAggregateOutputType = {
  id: string | null
  supplierId: string | null
  procurementId: string | null
  amount: runtime.Decimal | null
  paidAmount: runtime.Decimal | null
  dueDate: Date | null
  status: string | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AccountPayableCountAggregateOutputType = {
  id: number
  supplierId: number
  procurementId: number
  amount: number
  paidAmount: number
  dueDate: number
  status: number
  notes: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AccountPayableAvgAggregateInputType = {
  amount?: true
  paidAmount?: true
}

export type AccountPayableSumAggregateInputType = {
  amount?: true
  paidAmount?: true
}

export type AccountPayableMinAggregateInputType = {
  id?: true
  supplierId?: true
  procurementId?: true
  amount?: true
  paidAmount?: true
  dueDate?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type AccountPayableMaxAggregateInputType = {
  id?: true
  supplierId?: true
  procurementId?: true
  amount?: true
  paidAmount?: true
  dueDate?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
}

export type AccountPayableCountAggregateInputType = {
  id?: true
  supplierId?: true
  procurementId?: true
  amount?: true
  paidAmount?: true
  dueDate?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AccountPayableAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccountPayable to aggregate.
   */
  where?: Prisma.AccountPayableWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountPayables to fetch.
   */
  orderBy?: Prisma.AccountPayableOrderByWithRelationInput | Prisma.AccountPayableOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AccountPayableWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountPayables from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountPayables.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AccountPayables
  **/
  _count?: true | AccountPayableCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AccountPayableAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AccountPayableSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AccountPayableMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AccountPayableMaxAggregateInputType
}

export type GetAccountPayableAggregateType<T extends AccountPayableAggregateArgs> = {
      [P in keyof T & keyof AggregateAccountPayable]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAccountPayable[P]>
    : Prisma.GetScalarType<T[P], AggregateAccountPayable[P]>
}




export type AccountPayableGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AccountPayableWhereInput
  orderBy?: Prisma.AccountPayableOrderByWithAggregationInput | Prisma.AccountPayableOrderByWithAggregationInput[]
  by: Prisma.AccountPayableScalarFieldEnum[] | Prisma.AccountPayableScalarFieldEnum
  having?: Prisma.AccountPayableScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AccountPayableCountAggregateInputType | true
  _avg?: AccountPayableAvgAggregateInputType
  _sum?: AccountPayableSumAggregateInputType
  _min?: AccountPayableMinAggregateInputType
  _max?: AccountPayableMaxAggregateInputType
}

export type AccountPayableGroupByOutputType = {
  id: string
  supplierId: string
  procurementId: string | null
  amount: runtime.Decimal
  paidAmount: runtime.Decimal
  dueDate: Date | null
  status: string
  notes: string | null
  createdAt: Date
  updatedAt: Date
  _count: AccountPayableCountAggregateOutputType | null
  _avg: AccountPayableAvgAggregateOutputType | null
  _sum: AccountPayableSumAggregateOutputType | null
  _min: AccountPayableMinAggregateOutputType | null
  _max: AccountPayableMaxAggregateOutputType | null
}

export type GetAccountPayableGroupByPayload<T extends AccountPayableGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AccountPayableGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AccountPayableGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AccountPayableGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AccountPayableGroupByOutputType[P]>
      }
    >
  >



export type AccountPayableWhereInput = {
  AND?: Prisma.AccountPayableWhereInput | Prisma.AccountPayableWhereInput[]
  OR?: Prisma.AccountPayableWhereInput[]
  NOT?: Prisma.AccountPayableWhereInput | Prisma.AccountPayableWhereInput[]
  id?: Prisma.StringFilter<"AccountPayable"> | string
  supplierId?: Prisma.StringFilter<"AccountPayable"> | string
  procurementId?: Prisma.StringNullableFilter<"AccountPayable"> | string | null
  amount?: Prisma.DecimalFilter<"AccountPayable"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFilter<"AccountPayable"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Prisma.DateTimeNullableFilter<"AccountPayable"> | Date | string | null
  status?: Prisma.StringFilter<"AccountPayable"> | string
  notes?: Prisma.StringNullableFilter<"AccountPayable"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AccountPayable"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccountPayable"> | Date | string
  supplier?: Prisma.XOR<Prisma.SupplierScalarRelationFilter, Prisma.SupplierWhereInput>
  procurement?: Prisma.XOR<Prisma.ProcurementNullableScalarRelationFilter, Prisma.ProcurementWhereInput> | null
}

export type AccountPayableOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  procurementId?: Prisma.SortOrderInput | Prisma.SortOrder
  amount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  dueDate?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  supplier?: Prisma.SupplierOrderByWithRelationInput
  procurement?: Prisma.ProcurementOrderByWithRelationInput
}

export type AccountPayableWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AccountPayableWhereInput | Prisma.AccountPayableWhereInput[]
  OR?: Prisma.AccountPayableWhereInput[]
  NOT?: Prisma.AccountPayableWhereInput | Prisma.AccountPayableWhereInput[]
  supplierId?: Prisma.StringFilter<"AccountPayable"> | string
  procurementId?: Prisma.StringNullableFilter<"AccountPayable"> | string | null
  amount?: Prisma.DecimalFilter<"AccountPayable"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFilter<"AccountPayable"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Prisma.DateTimeNullableFilter<"AccountPayable"> | Date | string | null
  status?: Prisma.StringFilter<"AccountPayable"> | string
  notes?: Prisma.StringNullableFilter<"AccountPayable"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AccountPayable"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccountPayable"> | Date | string
  supplier?: Prisma.XOR<Prisma.SupplierScalarRelationFilter, Prisma.SupplierWhereInput>
  procurement?: Prisma.XOR<Prisma.ProcurementNullableScalarRelationFilter, Prisma.ProcurementWhereInput> | null
}, "id">

export type AccountPayableOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  procurementId?: Prisma.SortOrderInput | Prisma.SortOrder
  amount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  dueDate?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AccountPayableCountOrderByAggregateInput
  _avg?: Prisma.AccountPayableAvgOrderByAggregateInput
  _max?: Prisma.AccountPayableMaxOrderByAggregateInput
  _min?: Prisma.AccountPayableMinOrderByAggregateInput
  _sum?: Prisma.AccountPayableSumOrderByAggregateInput
}

export type AccountPayableScalarWhereWithAggregatesInput = {
  AND?: Prisma.AccountPayableScalarWhereWithAggregatesInput | Prisma.AccountPayableScalarWhereWithAggregatesInput[]
  OR?: Prisma.AccountPayableScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AccountPayableScalarWhereWithAggregatesInput | Prisma.AccountPayableScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AccountPayable"> | string
  supplierId?: Prisma.StringWithAggregatesFilter<"AccountPayable"> | string
  procurementId?: Prisma.StringNullableWithAggregatesFilter<"AccountPayable"> | string | null
  amount?: Prisma.DecimalWithAggregatesFilter<"AccountPayable"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalWithAggregatesFilter<"AccountPayable"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Prisma.DateTimeNullableWithAggregatesFilter<"AccountPayable"> | Date | string | null
  status?: Prisma.StringWithAggregatesFilter<"AccountPayable"> | string
  notes?: Prisma.StringNullableWithAggregatesFilter<"AccountPayable"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AccountPayable"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AccountPayable"> | Date | string
}

export type AccountPayableCreateInput = {
  id?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Date | string | null
  status?: string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  supplier: Prisma.SupplierCreateNestedOneWithoutAccountPayablesInput
  procurement?: Prisma.ProcurementCreateNestedOneWithoutPayablesInput
}

export type AccountPayableUncheckedCreateInput = {
  id?: string
  supplierId: string
  procurementId?: string | null
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Date | string | null
  status?: string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountPayableUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  supplier?: Prisma.SupplierUpdateOneRequiredWithoutAccountPayablesNestedInput
  procurement?: Prisma.ProcurementUpdateOneWithoutPayablesNestedInput
}

export type AccountPayableUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  supplierId?: Prisma.StringFieldUpdateOperationsInput | string
  procurementId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountPayableCreateManyInput = {
  id?: string
  supplierId: string
  procurementId?: string | null
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Date | string | null
  status?: string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountPayableUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountPayableUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  supplierId?: Prisma.StringFieldUpdateOperationsInput | string
  procurementId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountPayableListRelationFilter = {
  every?: Prisma.AccountPayableWhereInput
  some?: Prisma.AccountPayableWhereInput
  none?: Prisma.AccountPayableWhereInput
}

export type AccountPayableOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AccountPayableCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  procurementId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccountPayableAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
}

export type AccountPayableMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  procurementId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccountPayableMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  procurementId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
  dueDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AccountPayableSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
  paidAmount?: Prisma.SortOrder
}

export type AccountPayableCreateNestedManyWithoutSupplierInput = {
  create?: Prisma.XOR<Prisma.AccountPayableCreateWithoutSupplierInput, Prisma.AccountPayableUncheckedCreateWithoutSupplierInput> | Prisma.AccountPayableCreateWithoutSupplierInput[] | Prisma.AccountPayableUncheckedCreateWithoutSupplierInput[]
  connectOrCreate?: Prisma.AccountPayableCreateOrConnectWithoutSupplierInput | Prisma.AccountPayableCreateOrConnectWithoutSupplierInput[]
  createMany?: Prisma.AccountPayableCreateManySupplierInputEnvelope
  connect?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
}

export type AccountPayableUncheckedCreateNestedManyWithoutSupplierInput = {
  create?: Prisma.XOR<Prisma.AccountPayableCreateWithoutSupplierInput, Prisma.AccountPayableUncheckedCreateWithoutSupplierInput> | Prisma.AccountPayableCreateWithoutSupplierInput[] | Prisma.AccountPayableUncheckedCreateWithoutSupplierInput[]
  connectOrCreate?: Prisma.AccountPayableCreateOrConnectWithoutSupplierInput | Prisma.AccountPayableCreateOrConnectWithoutSupplierInput[]
  createMany?: Prisma.AccountPayableCreateManySupplierInputEnvelope
  connect?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
}

export type AccountPayableUpdateManyWithoutSupplierNestedInput = {
  create?: Prisma.XOR<Prisma.AccountPayableCreateWithoutSupplierInput, Prisma.AccountPayableUncheckedCreateWithoutSupplierInput> | Prisma.AccountPayableCreateWithoutSupplierInput[] | Prisma.AccountPayableUncheckedCreateWithoutSupplierInput[]
  connectOrCreate?: Prisma.AccountPayableCreateOrConnectWithoutSupplierInput | Prisma.AccountPayableCreateOrConnectWithoutSupplierInput[]
  upsert?: Prisma.AccountPayableUpsertWithWhereUniqueWithoutSupplierInput | Prisma.AccountPayableUpsertWithWhereUniqueWithoutSupplierInput[]
  createMany?: Prisma.AccountPayableCreateManySupplierInputEnvelope
  set?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
  disconnect?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
  delete?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
  connect?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
  update?: Prisma.AccountPayableUpdateWithWhereUniqueWithoutSupplierInput | Prisma.AccountPayableUpdateWithWhereUniqueWithoutSupplierInput[]
  updateMany?: Prisma.AccountPayableUpdateManyWithWhereWithoutSupplierInput | Prisma.AccountPayableUpdateManyWithWhereWithoutSupplierInput[]
  deleteMany?: Prisma.AccountPayableScalarWhereInput | Prisma.AccountPayableScalarWhereInput[]
}

export type AccountPayableUncheckedUpdateManyWithoutSupplierNestedInput = {
  create?: Prisma.XOR<Prisma.AccountPayableCreateWithoutSupplierInput, Prisma.AccountPayableUncheckedCreateWithoutSupplierInput> | Prisma.AccountPayableCreateWithoutSupplierInput[] | Prisma.AccountPayableUncheckedCreateWithoutSupplierInput[]
  connectOrCreate?: Prisma.AccountPayableCreateOrConnectWithoutSupplierInput | Prisma.AccountPayableCreateOrConnectWithoutSupplierInput[]
  upsert?: Prisma.AccountPayableUpsertWithWhereUniqueWithoutSupplierInput | Prisma.AccountPayableUpsertWithWhereUniqueWithoutSupplierInput[]
  createMany?: Prisma.AccountPayableCreateManySupplierInputEnvelope
  set?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
  disconnect?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
  delete?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
  connect?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
  update?: Prisma.AccountPayableUpdateWithWhereUniqueWithoutSupplierInput | Prisma.AccountPayableUpdateWithWhereUniqueWithoutSupplierInput[]
  updateMany?: Prisma.AccountPayableUpdateManyWithWhereWithoutSupplierInput | Prisma.AccountPayableUpdateManyWithWhereWithoutSupplierInput[]
  deleteMany?: Prisma.AccountPayableScalarWhereInput | Prisma.AccountPayableScalarWhereInput[]
}

export type AccountPayableCreateNestedManyWithoutProcurementInput = {
  create?: Prisma.XOR<Prisma.AccountPayableCreateWithoutProcurementInput, Prisma.AccountPayableUncheckedCreateWithoutProcurementInput> | Prisma.AccountPayableCreateWithoutProcurementInput[] | Prisma.AccountPayableUncheckedCreateWithoutProcurementInput[]
  connectOrCreate?: Prisma.AccountPayableCreateOrConnectWithoutProcurementInput | Prisma.AccountPayableCreateOrConnectWithoutProcurementInput[]
  createMany?: Prisma.AccountPayableCreateManyProcurementInputEnvelope
  connect?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
}

export type AccountPayableUncheckedCreateNestedManyWithoutProcurementInput = {
  create?: Prisma.XOR<Prisma.AccountPayableCreateWithoutProcurementInput, Prisma.AccountPayableUncheckedCreateWithoutProcurementInput> | Prisma.AccountPayableCreateWithoutProcurementInput[] | Prisma.AccountPayableUncheckedCreateWithoutProcurementInput[]
  connectOrCreate?: Prisma.AccountPayableCreateOrConnectWithoutProcurementInput | Prisma.AccountPayableCreateOrConnectWithoutProcurementInput[]
  createMany?: Prisma.AccountPayableCreateManyProcurementInputEnvelope
  connect?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
}

export type AccountPayableUpdateManyWithoutProcurementNestedInput = {
  create?: Prisma.XOR<Prisma.AccountPayableCreateWithoutProcurementInput, Prisma.AccountPayableUncheckedCreateWithoutProcurementInput> | Prisma.AccountPayableCreateWithoutProcurementInput[] | Prisma.AccountPayableUncheckedCreateWithoutProcurementInput[]
  connectOrCreate?: Prisma.AccountPayableCreateOrConnectWithoutProcurementInput | Prisma.AccountPayableCreateOrConnectWithoutProcurementInput[]
  upsert?: Prisma.AccountPayableUpsertWithWhereUniqueWithoutProcurementInput | Prisma.AccountPayableUpsertWithWhereUniqueWithoutProcurementInput[]
  createMany?: Prisma.AccountPayableCreateManyProcurementInputEnvelope
  set?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
  disconnect?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
  delete?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
  connect?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
  update?: Prisma.AccountPayableUpdateWithWhereUniqueWithoutProcurementInput | Prisma.AccountPayableUpdateWithWhereUniqueWithoutProcurementInput[]
  updateMany?: Prisma.AccountPayableUpdateManyWithWhereWithoutProcurementInput | Prisma.AccountPayableUpdateManyWithWhereWithoutProcurementInput[]
  deleteMany?: Prisma.AccountPayableScalarWhereInput | Prisma.AccountPayableScalarWhereInput[]
}

export type AccountPayableUncheckedUpdateManyWithoutProcurementNestedInput = {
  create?: Prisma.XOR<Prisma.AccountPayableCreateWithoutProcurementInput, Prisma.AccountPayableUncheckedCreateWithoutProcurementInput> | Prisma.AccountPayableCreateWithoutProcurementInput[] | Prisma.AccountPayableUncheckedCreateWithoutProcurementInput[]
  connectOrCreate?: Prisma.AccountPayableCreateOrConnectWithoutProcurementInput | Prisma.AccountPayableCreateOrConnectWithoutProcurementInput[]
  upsert?: Prisma.AccountPayableUpsertWithWhereUniqueWithoutProcurementInput | Prisma.AccountPayableUpsertWithWhereUniqueWithoutProcurementInput[]
  createMany?: Prisma.AccountPayableCreateManyProcurementInputEnvelope
  set?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
  disconnect?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
  delete?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
  connect?: Prisma.AccountPayableWhereUniqueInput | Prisma.AccountPayableWhereUniqueInput[]
  update?: Prisma.AccountPayableUpdateWithWhereUniqueWithoutProcurementInput | Prisma.AccountPayableUpdateWithWhereUniqueWithoutProcurementInput[]
  updateMany?: Prisma.AccountPayableUpdateManyWithWhereWithoutProcurementInput | Prisma.AccountPayableUpdateManyWithWhereWithoutProcurementInput[]
  deleteMany?: Prisma.AccountPayableScalarWhereInput | Prisma.AccountPayableScalarWhereInput[]
}

export type AccountPayableCreateWithoutSupplierInput = {
  id?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Date | string | null
  status?: string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  procurement?: Prisma.ProcurementCreateNestedOneWithoutPayablesInput
}

export type AccountPayableUncheckedCreateWithoutSupplierInput = {
  id?: string
  procurementId?: string | null
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Date | string | null
  status?: string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountPayableCreateOrConnectWithoutSupplierInput = {
  where: Prisma.AccountPayableWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountPayableCreateWithoutSupplierInput, Prisma.AccountPayableUncheckedCreateWithoutSupplierInput>
}

export type AccountPayableCreateManySupplierInputEnvelope = {
  data: Prisma.AccountPayableCreateManySupplierInput | Prisma.AccountPayableCreateManySupplierInput[]
  skipDuplicates?: boolean
}

export type AccountPayableUpsertWithWhereUniqueWithoutSupplierInput = {
  where: Prisma.AccountPayableWhereUniqueInput
  update: Prisma.XOR<Prisma.AccountPayableUpdateWithoutSupplierInput, Prisma.AccountPayableUncheckedUpdateWithoutSupplierInput>
  create: Prisma.XOR<Prisma.AccountPayableCreateWithoutSupplierInput, Prisma.AccountPayableUncheckedCreateWithoutSupplierInput>
}

export type AccountPayableUpdateWithWhereUniqueWithoutSupplierInput = {
  where: Prisma.AccountPayableWhereUniqueInput
  data: Prisma.XOR<Prisma.AccountPayableUpdateWithoutSupplierInput, Prisma.AccountPayableUncheckedUpdateWithoutSupplierInput>
}

export type AccountPayableUpdateManyWithWhereWithoutSupplierInput = {
  where: Prisma.AccountPayableScalarWhereInput
  data: Prisma.XOR<Prisma.AccountPayableUpdateManyMutationInput, Prisma.AccountPayableUncheckedUpdateManyWithoutSupplierInput>
}

export type AccountPayableScalarWhereInput = {
  AND?: Prisma.AccountPayableScalarWhereInput | Prisma.AccountPayableScalarWhereInput[]
  OR?: Prisma.AccountPayableScalarWhereInput[]
  NOT?: Prisma.AccountPayableScalarWhereInput | Prisma.AccountPayableScalarWhereInput[]
  id?: Prisma.StringFilter<"AccountPayable"> | string
  supplierId?: Prisma.StringFilter<"AccountPayable"> | string
  procurementId?: Prisma.StringNullableFilter<"AccountPayable"> | string | null
  amount?: Prisma.DecimalFilter<"AccountPayable"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFilter<"AccountPayable"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Prisma.DateTimeNullableFilter<"AccountPayable"> | Date | string | null
  status?: Prisma.StringFilter<"AccountPayable"> | string
  notes?: Prisma.StringNullableFilter<"AccountPayable"> | string | null
  createdAt?: Prisma.DateTimeFilter<"AccountPayable"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AccountPayable"> | Date | string
}

export type AccountPayableCreateWithoutProcurementInput = {
  id?: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Date | string | null
  status?: string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  supplier: Prisma.SupplierCreateNestedOneWithoutAccountPayablesInput
}

export type AccountPayableUncheckedCreateWithoutProcurementInput = {
  id?: string
  supplierId: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Date | string | null
  status?: string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountPayableCreateOrConnectWithoutProcurementInput = {
  where: Prisma.AccountPayableWhereUniqueInput
  create: Prisma.XOR<Prisma.AccountPayableCreateWithoutProcurementInput, Prisma.AccountPayableUncheckedCreateWithoutProcurementInput>
}

export type AccountPayableCreateManyProcurementInputEnvelope = {
  data: Prisma.AccountPayableCreateManyProcurementInput | Prisma.AccountPayableCreateManyProcurementInput[]
  skipDuplicates?: boolean
}

export type AccountPayableUpsertWithWhereUniqueWithoutProcurementInput = {
  where: Prisma.AccountPayableWhereUniqueInput
  update: Prisma.XOR<Prisma.AccountPayableUpdateWithoutProcurementInput, Prisma.AccountPayableUncheckedUpdateWithoutProcurementInput>
  create: Prisma.XOR<Prisma.AccountPayableCreateWithoutProcurementInput, Prisma.AccountPayableUncheckedCreateWithoutProcurementInput>
}

export type AccountPayableUpdateWithWhereUniqueWithoutProcurementInput = {
  where: Prisma.AccountPayableWhereUniqueInput
  data: Prisma.XOR<Prisma.AccountPayableUpdateWithoutProcurementInput, Prisma.AccountPayableUncheckedUpdateWithoutProcurementInput>
}

export type AccountPayableUpdateManyWithWhereWithoutProcurementInput = {
  where: Prisma.AccountPayableScalarWhereInput
  data: Prisma.XOR<Prisma.AccountPayableUpdateManyMutationInput, Prisma.AccountPayableUncheckedUpdateManyWithoutProcurementInput>
}

export type AccountPayableCreateManySupplierInput = {
  id?: string
  procurementId?: string | null
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Date | string | null
  status?: string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountPayableUpdateWithoutSupplierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  procurement?: Prisma.ProcurementUpdateOneWithoutPayablesNestedInput
}

export type AccountPayableUncheckedUpdateWithoutSupplierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  procurementId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountPayableUncheckedUpdateManyWithoutSupplierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  procurementId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountPayableCreateManyProcurementInput = {
  id?: string
  supplierId: string
  amount: runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Date | string | null
  status?: string
  notes?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AccountPayableUpdateWithoutProcurementInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  supplier?: Prisma.SupplierUpdateOneRequiredWithoutAccountPayablesNestedInput
}

export type AccountPayableUncheckedUpdateWithoutProcurementInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  supplierId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AccountPayableUncheckedUpdateManyWithoutProcurementInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  supplierId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  paidAmount?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  dueDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AccountPayableSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  supplierId?: boolean
  procurementId?: boolean
  amount?: boolean
  paidAmount?: boolean
  dueDate?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
  procurement?: boolean | Prisma.AccountPayable$procurementArgs<ExtArgs>
}, ExtArgs["result"]["accountPayable"]>

export type AccountPayableSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  supplierId?: boolean
  procurementId?: boolean
  amount?: boolean
  paidAmount?: boolean
  dueDate?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
  procurement?: boolean | Prisma.AccountPayable$procurementArgs<ExtArgs>
}, ExtArgs["result"]["accountPayable"]>

export type AccountPayableSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  supplierId?: boolean
  procurementId?: boolean
  amount?: boolean
  paidAmount?: boolean
  dueDate?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
  procurement?: boolean | Prisma.AccountPayable$procurementArgs<ExtArgs>
}, ExtArgs["result"]["accountPayable"]>

export type AccountPayableSelectScalar = {
  id?: boolean
  supplierId?: boolean
  procurementId?: boolean
  amount?: boolean
  paidAmount?: boolean
  dueDate?: boolean
  status?: boolean
  notes?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AccountPayableOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "supplierId" | "procurementId" | "amount" | "paidAmount" | "dueDate" | "status" | "notes" | "createdAt" | "updatedAt", ExtArgs["result"]["accountPayable"]>
export type AccountPayableInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
  procurement?: boolean | Prisma.AccountPayable$procurementArgs<ExtArgs>
}
export type AccountPayableIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
  procurement?: boolean | Prisma.AccountPayable$procurementArgs<ExtArgs>
}
export type AccountPayableIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
  procurement?: boolean | Prisma.AccountPayable$procurementArgs<ExtArgs>
}

export type $AccountPayablePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AccountPayable"
  objects: {
    supplier: Prisma.$SupplierPayload<ExtArgs>
    procurement: Prisma.$ProcurementPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    supplierId: string
    procurementId: string | null
    amount: runtime.Decimal
    paidAmount: runtime.Decimal
    dueDate: Date | null
    status: string
    notes: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["accountPayable"]>
  composites: {}
}

export type AccountPayableGetPayload<S extends boolean | null | undefined | AccountPayableDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AccountPayablePayload, S>

export type AccountPayableCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AccountPayableFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AccountPayableCountAggregateInputType | true
  }

export interface AccountPayableDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AccountPayable'], meta: { name: 'AccountPayable' } }
  /**
   * Find zero or one AccountPayable that matches the filter.
   * @param {AccountPayableFindUniqueArgs} args - Arguments to find a AccountPayable
   * @example
   * // Get one AccountPayable
   * const accountPayable = await prisma.accountPayable.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AccountPayableFindUniqueArgs>(args: Prisma.SelectSubset<T, AccountPayableFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AccountPayableClient<runtime.Types.Result.GetResult<Prisma.$AccountPayablePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AccountPayable that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AccountPayableFindUniqueOrThrowArgs} args - Arguments to find a AccountPayable
   * @example
   * // Get one AccountPayable
   * const accountPayable = await prisma.accountPayable.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AccountPayableFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AccountPayableFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccountPayableClient<runtime.Types.Result.GetResult<Prisma.$AccountPayablePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccountPayable that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountPayableFindFirstArgs} args - Arguments to find a AccountPayable
   * @example
   * // Get one AccountPayable
   * const accountPayable = await prisma.accountPayable.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AccountPayableFindFirstArgs>(args?: Prisma.SelectSubset<T, AccountPayableFindFirstArgs<ExtArgs>>): Prisma.Prisma__AccountPayableClient<runtime.Types.Result.GetResult<Prisma.$AccountPayablePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AccountPayable that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountPayableFindFirstOrThrowArgs} args - Arguments to find a AccountPayable
   * @example
   * // Get one AccountPayable
   * const accountPayable = await prisma.accountPayable.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AccountPayableFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AccountPayableFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AccountPayableClient<runtime.Types.Result.GetResult<Prisma.$AccountPayablePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AccountPayables that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountPayableFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AccountPayables
   * const accountPayables = await prisma.accountPayable.findMany()
   * 
   * // Get first 10 AccountPayables
   * const accountPayables = await prisma.accountPayable.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const accountPayableWithIdOnly = await prisma.accountPayable.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AccountPayableFindManyArgs>(args?: Prisma.SelectSubset<T, AccountPayableFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountPayablePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AccountPayable.
   * @param {AccountPayableCreateArgs} args - Arguments to create a AccountPayable.
   * @example
   * // Create one AccountPayable
   * const AccountPayable = await prisma.accountPayable.create({
   *   data: {
   *     // ... data to create a AccountPayable
   *   }
   * })
   * 
   */
  create<T extends AccountPayableCreateArgs>(args: Prisma.SelectSubset<T, AccountPayableCreateArgs<ExtArgs>>): Prisma.Prisma__AccountPayableClient<runtime.Types.Result.GetResult<Prisma.$AccountPayablePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AccountPayables.
   * @param {AccountPayableCreateManyArgs} args - Arguments to create many AccountPayables.
   * @example
   * // Create many AccountPayables
   * const accountPayable = await prisma.accountPayable.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AccountPayableCreateManyArgs>(args?: Prisma.SelectSubset<T, AccountPayableCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AccountPayables and returns the data saved in the database.
   * @param {AccountPayableCreateManyAndReturnArgs} args - Arguments to create many AccountPayables.
   * @example
   * // Create many AccountPayables
   * const accountPayable = await prisma.accountPayable.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AccountPayables and only return the `id`
   * const accountPayableWithIdOnly = await prisma.accountPayable.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AccountPayableCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AccountPayableCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountPayablePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AccountPayable.
   * @param {AccountPayableDeleteArgs} args - Arguments to delete one AccountPayable.
   * @example
   * // Delete one AccountPayable
   * const AccountPayable = await prisma.accountPayable.delete({
   *   where: {
   *     // ... filter to delete one AccountPayable
   *   }
   * })
   * 
   */
  delete<T extends AccountPayableDeleteArgs>(args: Prisma.SelectSubset<T, AccountPayableDeleteArgs<ExtArgs>>): Prisma.Prisma__AccountPayableClient<runtime.Types.Result.GetResult<Prisma.$AccountPayablePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AccountPayable.
   * @param {AccountPayableUpdateArgs} args - Arguments to update one AccountPayable.
   * @example
   * // Update one AccountPayable
   * const accountPayable = await prisma.accountPayable.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AccountPayableUpdateArgs>(args: Prisma.SelectSubset<T, AccountPayableUpdateArgs<ExtArgs>>): Prisma.Prisma__AccountPayableClient<runtime.Types.Result.GetResult<Prisma.$AccountPayablePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AccountPayables.
   * @param {AccountPayableDeleteManyArgs} args - Arguments to filter AccountPayables to delete.
   * @example
   * // Delete a few AccountPayables
   * const { count } = await prisma.accountPayable.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AccountPayableDeleteManyArgs>(args?: Prisma.SelectSubset<T, AccountPayableDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccountPayables.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountPayableUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AccountPayables
   * const accountPayable = await prisma.accountPayable.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AccountPayableUpdateManyArgs>(args: Prisma.SelectSubset<T, AccountPayableUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AccountPayables and returns the data updated in the database.
   * @param {AccountPayableUpdateManyAndReturnArgs} args - Arguments to update many AccountPayables.
   * @example
   * // Update many AccountPayables
   * const accountPayable = await prisma.accountPayable.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AccountPayables and only return the `id`
   * const accountPayableWithIdOnly = await prisma.accountPayable.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AccountPayableUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AccountPayableUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AccountPayablePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AccountPayable.
   * @param {AccountPayableUpsertArgs} args - Arguments to update or create a AccountPayable.
   * @example
   * // Update or create a AccountPayable
   * const accountPayable = await prisma.accountPayable.upsert({
   *   create: {
   *     // ... data to create a AccountPayable
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AccountPayable we want to update
   *   }
   * })
   */
  upsert<T extends AccountPayableUpsertArgs>(args: Prisma.SelectSubset<T, AccountPayableUpsertArgs<ExtArgs>>): Prisma.Prisma__AccountPayableClient<runtime.Types.Result.GetResult<Prisma.$AccountPayablePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AccountPayables.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountPayableCountArgs} args - Arguments to filter AccountPayables to count.
   * @example
   * // Count the number of AccountPayables
   * const count = await prisma.accountPayable.count({
   *   where: {
   *     // ... the filter for the AccountPayables we want to count
   *   }
   * })
  **/
  count<T extends AccountPayableCountArgs>(
    args?: Prisma.Subset<T, AccountPayableCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AccountPayableCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AccountPayable.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountPayableAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AccountPayableAggregateArgs>(args: Prisma.Subset<T, AccountPayableAggregateArgs>): Prisma.PrismaPromise<GetAccountPayableAggregateType<T>>

  /**
   * Group by AccountPayable.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AccountPayableGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AccountPayableGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AccountPayableGroupByArgs['orderBy'] }
      : { orderBy?: AccountPayableGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AccountPayableGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAccountPayableGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AccountPayable model
 */
readonly fields: AccountPayableFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AccountPayable.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AccountPayableClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  supplier<T extends Prisma.SupplierDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SupplierDefaultArgs<ExtArgs>>): Prisma.Prisma__SupplierClient<runtime.Types.Result.GetResult<Prisma.$SupplierPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  procurement<T extends Prisma.AccountPayable$procurementArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AccountPayable$procurementArgs<ExtArgs>>): Prisma.Prisma__ProcurementClient<runtime.Types.Result.GetResult<Prisma.$ProcurementPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AccountPayable model
 */
export interface AccountPayableFieldRefs {
  readonly id: Prisma.FieldRef<"AccountPayable", 'String'>
  readonly supplierId: Prisma.FieldRef<"AccountPayable", 'String'>
  readonly procurementId: Prisma.FieldRef<"AccountPayable", 'String'>
  readonly amount: Prisma.FieldRef<"AccountPayable", 'Decimal'>
  readonly paidAmount: Prisma.FieldRef<"AccountPayable", 'Decimal'>
  readonly dueDate: Prisma.FieldRef<"AccountPayable", 'DateTime'>
  readonly status: Prisma.FieldRef<"AccountPayable", 'String'>
  readonly notes: Prisma.FieldRef<"AccountPayable", 'String'>
  readonly createdAt: Prisma.FieldRef<"AccountPayable", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AccountPayable", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AccountPayable findUnique
 */
export type AccountPayableFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountPayable
   */
  select?: Prisma.AccountPayableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountPayable
   */
  omit?: Prisma.AccountPayableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountPayableInclude<ExtArgs> | null
  /**
   * Filter, which AccountPayable to fetch.
   */
  where: Prisma.AccountPayableWhereUniqueInput
}

/**
 * AccountPayable findUniqueOrThrow
 */
export type AccountPayableFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountPayable
   */
  select?: Prisma.AccountPayableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountPayable
   */
  omit?: Prisma.AccountPayableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountPayableInclude<ExtArgs> | null
  /**
   * Filter, which AccountPayable to fetch.
   */
  where: Prisma.AccountPayableWhereUniqueInput
}

/**
 * AccountPayable findFirst
 */
export type AccountPayableFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountPayable
   */
  select?: Prisma.AccountPayableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountPayable
   */
  omit?: Prisma.AccountPayableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountPayableInclude<ExtArgs> | null
  /**
   * Filter, which AccountPayable to fetch.
   */
  where?: Prisma.AccountPayableWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountPayables to fetch.
   */
  orderBy?: Prisma.AccountPayableOrderByWithRelationInput | Prisma.AccountPayableOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccountPayables.
   */
  cursor?: Prisma.AccountPayableWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountPayables from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountPayables.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccountPayables.
   */
  distinct?: Prisma.AccountPayableScalarFieldEnum | Prisma.AccountPayableScalarFieldEnum[]
}

/**
 * AccountPayable findFirstOrThrow
 */
export type AccountPayableFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountPayable
   */
  select?: Prisma.AccountPayableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountPayable
   */
  omit?: Prisma.AccountPayableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountPayableInclude<ExtArgs> | null
  /**
   * Filter, which AccountPayable to fetch.
   */
  where?: Prisma.AccountPayableWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountPayables to fetch.
   */
  orderBy?: Prisma.AccountPayableOrderByWithRelationInput | Prisma.AccountPayableOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AccountPayables.
   */
  cursor?: Prisma.AccountPayableWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountPayables from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountPayables.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccountPayables.
   */
  distinct?: Prisma.AccountPayableScalarFieldEnum | Prisma.AccountPayableScalarFieldEnum[]
}

/**
 * AccountPayable findMany
 */
export type AccountPayableFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountPayable
   */
  select?: Prisma.AccountPayableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountPayable
   */
  omit?: Prisma.AccountPayableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountPayableInclude<ExtArgs> | null
  /**
   * Filter, which AccountPayables to fetch.
   */
  where?: Prisma.AccountPayableWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AccountPayables to fetch.
   */
  orderBy?: Prisma.AccountPayableOrderByWithRelationInput | Prisma.AccountPayableOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AccountPayables.
   */
  cursor?: Prisma.AccountPayableWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AccountPayables from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AccountPayables.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AccountPayables.
   */
  distinct?: Prisma.AccountPayableScalarFieldEnum | Prisma.AccountPayableScalarFieldEnum[]
}

/**
 * AccountPayable create
 */
export type AccountPayableCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountPayable
   */
  select?: Prisma.AccountPayableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountPayable
   */
  omit?: Prisma.AccountPayableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountPayableInclude<ExtArgs> | null
  /**
   * The data needed to create a AccountPayable.
   */
  data: Prisma.XOR<Prisma.AccountPayableCreateInput, Prisma.AccountPayableUncheckedCreateInput>
}

/**
 * AccountPayable createMany
 */
export type AccountPayableCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AccountPayables.
   */
  data: Prisma.AccountPayableCreateManyInput | Prisma.AccountPayableCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AccountPayable createManyAndReturn
 */
export type AccountPayableCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountPayable
   */
  select?: Prisma.AccountPayableSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccountPayable
   */
  omit?: Prisma.AccountPayableOmit<ExtArgs> | null
  /**
   * The data used to create many AccountPayables.
   */
  data: Prisma.AccountPayableCreateManyInput | Prisma.AccountPayableCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountPayableIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AccountPayable update
 */
export type AccountPayableUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountPayable
   */
  select?: Prisma.AccountPayableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountPayable
   */
  omit?: Prisma.AccountPayableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountPayableInclude<ExtArgs> | null
  /**
   * The data needed to update a AccountPayable.
   */
  data: Prisma.XOR<Prisma.AccountPayableUpdateInput, Prisma.AccountPayableUncheckedUpdateInput>
  /**
   * Choose, which AccountPayable to update.
   */
  where: Prisma.AccountPayableWhereUniqueInput
}

/**
 * AccountPayable updateMany
 */
export type AccountPayableUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AccountPayables.
   */
  data: Prisma.XOR<Prisma.AccountPayableUpdateManyMutationInput, Prisma.AccountPayableUncheckedUpdateManyInput>
  /**
   * Filter which AccountPayables to update
   */
  where?: Prisma.AccountPayableWhereInput
  /**
   * Limit how many AccountPayables to update.
   */
  limit?: number
}

/**
 * AccountPayable updateManyAndReturn
 */
export type AccountPayableUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountPayable
   */
  select?: Prisma.AccountPayableSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AccountPayable
   */
  omit?: Prisma.AccountPayableOmit<ExtArgs> | null
  /**
   * The data used to update AccountPayables.
   */
  data: Prisma.XOR<Prisma.AccountPayableUpdateManyMutationInput, Prisma.AccountPayableUncheckedUpdateManyInput>
  /**
   * Filter which AccountPayables to update
   */
  where?: Prisma.AccountPayableWhereInput
  /**
   * Limit how many AccountPayables to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountPayableIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AccountPayable upsert
 */
export type AccountPayableUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountPayable
   */
  select?: Prisma.AccountPayableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountPayable
   */
  omit?: Prisma.AccountPayableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountPayableInclude<ExtArgs> | null
  /**
   * The filter to search for the AccountPayable to update in case it exists.
   */
  where: Prisma.AccountPayableWhereUniqueInput
  /**
   * In case the AccountPayable found by the `where` argument doesn't exist, create a new AccountPayable with this data.
   */
  create: Prisma.XOR<Prisma.AccountPayableCreateInput, Prisma.AccountPayableUncheckedCreateInput>
  /**
   * In case the AccountPayable was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AccountPayableUpdateInput, Prisma.AccountPayableUncheckedUpdateInput>
}

/**
 * AccountPayable delete
 */
export type AccountPayableDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountPayable
   */
  select?: Prisma.AccountPayableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountPayable
   */
  omit?: Prisma.AccountPayableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountPayableInclude<ExtArgs> | null
  /**
   * Filter which AccountPayable to delete.
   */
  where: Prisma.AccountPayableWhereUniqueInput
}

/**
 * AccountPayable deleteMany
 */
export type AccountPayableDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AccountPayables to delete
   */
  where?: Prisma.AccountPayableWhereInput
  /**
   * Limit how many AccountPayables to delete.
   */
  limit?: number
}

/**
 * AccountPayable.procurement
 */
export type AccountPayable$procurementArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Procurement
   */
  select?: Prisma.ProcurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Procurement
   */
  omit?: Prisma.ProcurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProcurementInclude<ExtArgs> | null
  where?: Prisma.ProcurementWhereInput
}

/**
 * AccountPayable without action
 */
export type AccountPayableDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AccountPayable
   */
  select?: Prisma.AccountPayableSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AccountPayable
   */
  omit?: Prisma.AccountPayableOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AccountPayableInclude<ExtArgs> | null
}
