
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `BusinessConfig` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model BusinessConfig
 * 
 */
export type BusinessConfigModel = runtime.Types.Result.DefaultSelection<Prisma.$BusinessConfigPayload>

export type AggregateBusinessConfig = {
  _count: BusinessConfigCountAggregateOutputType | null
  _min: BusinessConfigMinAggregateOutputType | null
  _max: BusinessConfigMaxAggregateOutputType | null
}

export type BusinessConfigMinAggregateOutputType = {
  id: string | null
  key: string | null
  value: string | null
}

export type BusinessConfigMaxAggregateOutputType = {
  id: string | null
  key: string | null
  value: string | null
}

export type BusinessConfigCountAggregateOutputType = {
  id: number
  key: number
  value: number
  _all: number
}


export type BusinessConfigMinAggregateInputType = {
  id?: true
  key?: true
  value?: true
}

export type BusinessConfigMaxAggregateInputType = {
  id?: true
  key?: true
  value?: true
}

export type BusinessConfigCountAggregateInputType = {
  id?: true
  key?: true
  value?: true
  _all?: true
}

export type BusinessConfigAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BusinessConfig to aggregate.
   */
  where?: Prisma.BusinessConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BusinessConfigs to fetch.
   */
  orderBy?: Prisma.BusinessConfigOrderByWithRelationInput | Prisma.BusinessConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BusinessConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BusinessConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BusinessConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned BusinessConfigs
  **/
  _count?: true | BusinessConfigCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BusinessConfigMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BusinessConfigMaxAggregateInputType
}

export type GetBusinessConfigAggregateType<T extends BusinessConfigAggregateArgs> = {
      [P in keyof T & keyof AggregateBusinessConfig]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBusinessConfig[P]>
    : Prisma.GetScalarType<T[P], AggregateBusinessConfig[P]>
}




export type BusinessConfigGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BusinessConfigWhereInput
  orderBy?: Prisma.BusinessConfigOrderByWithAggregationInput | Prisma.BusinessConfigOrderByWithAggregationInput[]
  by: Prisma.BusinessConfigScalarFieldEnum[] | Prisma.BusinessConfigScalarFieldEnum
  having?: Prisma.BusinessConfigScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BusinessConfigCountAggregateInputType | true
  _min?: BusinessConfigMinAggregateInputType
  _max?: BusinessConfigMaxAggregateInputType
}

export type BusinessConfigGroupByOutputType = {
  id: string
  key: string
  value: string
  _count: BusinessConfigCountAggregateOutputType | null
  _min: BusinessConfigMinAggregateOutputType | null
  _max: BusinessConfigMaxAggregateOutputType | null
}

export type GetBusinessConfigGroupByPayload<T extends BusinessConfigGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BusinessConfigGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BusinessConfigGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BusinessConfigGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BusinessConfigGroupByOutputType[P]>
      }
    >
  >



export type BusinessConfigWhereInput = {
  AND?: Prisma.BusinessConfigWhereInput | Prisma.BusinessConfigWhereInput[]
  OR?: Prisma.BusinessConfigWhereInput[]
  NOT?: Prisma.BusinessConfigWhereInput | Prisma.BusinessConfigWhereInput[]
  id?: Prisma.StringFilter<"BusinessConfig"> | string
  key?: Prisma.StringFilter<"BusinessConfig"> | string
  value?: Prisma.StringFilter<"BusinessConfig"> | string
}

export type BusinessConfigOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
}

export type BusinessConfigWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  key?: string
  AND?: Prisma.BusinessConfigWhereInput | Prisma.BusinessConfigWhereInput[]
  OR?: Prisma.BusinessConfigWhereInput[]
  NOT?: Prisma.BusinessConfigWhereInput | Prisma.BusinessConfigWhereInput[]
  value?: Prisma.StringFilter<"BusinessConfig"> | string
}, "id" | "key">

export type BusinessConfigOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
  _count?: Prisma.BusinessConfigCountOrderByAggregateInput
  _max?: Prisma.BusinessConfigMaxOrderByAggregateInput
  _min?: Prisma.BusinessConfigMinOrderByAggregateInput
}

export type BusinessConfigScalarWhereWithAggregatesInput = {
  AND?: Prisma.BusinessConfigScalarWhereWithAggregatesInput | Prisma.BusinessConfigScalarWhereWithAggregatesInput[]
  OR?: Prisma.BusinessConfigScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BusinessConfigScalarWhereWithAggregatesInput | Prisma.BusinessConfigScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"BusinessConfig"> | string
  key?: Prisma.StringWithAggregatesFilter<"BusinessConfig"> | string
  value?: Prisma.StringWithAggregatesFilter<"BusinessConfig"> | string
}

export type BusinessConfigCreateInput = {
  id?: string
  key: string
  value: string
}

export type BusinessConfigUncheckedCreateInput = {
  id?: string
  key: string
  value: string
}

export type BusinessConfigUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BusinessConfigUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BusinessConfigCreateManyInput = {
  id?: string
  key: string
  value: string
}

export type BusinessConfigUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BusinessConfigUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BusinessConfigCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
}

export type BusinessConfigMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
}

export type BusinessConfigMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  value?: Prisma.SortOrder
}



export type BusinessConfigSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  value?: boolean
}, ExtArgs["result"]["businessConfig"]>

export type BusinessConfigSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  value?: boolean
}, ExtArgs["result"]["businessConfig"]>

export type BusinessConfigSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  value?: boolean
}, ExtArgs["result"]["businessConfig"]>

export type BusinessConfigSelectScalar = {
  id?: boolean
  key?: boolean
  value?: boolean
}

export type BusinessConfigOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "key" | "value", ExtArgs["result"]["businessConfig"]>

export type $BusinessConfigPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "BusinessConfig"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    key: string
    value: string
  }, ExtArgs["result"]["businessConfig"]>
  composites: {}
}

export type BusinessConfigGetPayload<S extends boolean | null | undefined | BusinessConfigDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BusinessConfigPayload, S>

export type BusinessConfigCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BusinessConfigFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BusinessConfigCountAggregateInputType | true
  }

export interface BusinessConfigDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['BusinessConfig'], meta: { name: 'BusinessConfig' } }
  /**
   * Find zero or one BusinessConfig that matches the filter.
   * @param {BusinessConfigFindUniqueArgs} args - Arguments to find a BusinessConfig
   * @example
   * // Get one BusinessConfig
   * const businessConfig = await prisma.businessConfig.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BusinessConfigFindUniqueArgs>(args: Prisma.SelectSubset<T, BusinessConfigFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BusinessConfigClient<runtime.Types.Result.GetResult<Prisma.$BusinessConfigPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one BusinessConfig that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BusinessConfigFindUniqueOrThrowArgs} args - Arguments to find a BusinessConfig
   * @example
   * // Get one BusinessConfig
   * const businessConfig = await prisma.businessConfig.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BusinessConfigFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BusinessConfigFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BusinessConfigClient<runtime.Types.Result.GetResult<Prisma.$BusinessConfigPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BusinessConfig that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BusinessConfigFindFirstArgs} args - Arguments to find a BusinessConfig
   * @example
   * // Get one BusinessConfig
   * const businessConfig = await prisma.businessConfig.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BusinessConfigFindFirstArgs>(args?: Prisma.SelectSubset<T, BusinessConfigFindFirstArgs<ExtArgs>>): Prisma.Prisma__BusinessConfigClient<runtime.Types.Result.GetResult<Prisma.$BusinessConfigPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first BusinessConfig that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BusinessConfigFindFirstOrThrowArgs} args - Arguments to find a BusinessConfig
   * @example
   * // Get one BusinessConfig
   * const businessConfig = await prisma.businessConfig.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BusinessConfigFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BusinessConfigFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BusinessConfigClient<runtime.Types.Result.GetResult<Prisma.$BusinessConfigPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more BusinessConfigs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BusinessConfigFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all BusinessConfigs
   * const businessConfigs = await prisma.businessConfig.findMany()
   * 
   * // Get first 10 BusinessConfigs
   * const businessConfigs = await prisma.businessConfig.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const businessConfigWithIdOnly = await prisma.businessConfig.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BusinessConfigFindManyArgs>(args?: Prisma.SelectSubset<T, BusinessConfigFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BusinessConfigPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a BusinessConfig.
   * @param {BusinessConfigCreateArgs} args - Arguments to create a BusinessConfig.
   * @example
   * // Create one BusinessConfig
   * const BusinessConfig = await prisma.businessConfig.create({
   *   data: {
   *     // ... data to create a BusinessConfig
   *   }
   * })
   * 
   */
  create<T extends BusinessConfigCreateArgs>(args: Prisma.SelectSubset<T, BusinessConfigCreateArgs<ExtArgs>>): Prisma.Prisma__BusinessConfigClient<runtime.Types.Result.GetResult<Prisma.$BusinessConfigPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many BusinessConfigs.
   * @param {BusinessConfigCreateManyArgs} args - Arguments to create many BusinessConfigs.
   * @example
   * // Create many BusinessConfigs
   * const businessConfig = await prisma.businessConfig.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BusinessConfigCreateManyArgs>(args?: Prisma.SelectSubset<T, BusinessConfigCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many BusinessConfigs and returns the data saved in the database.
   * @param {BusinessConfigCreateManyAndReturnArgs} args - Arguments to create many BusinessConfigs.
   * @example
   * // Create many BusinessConfigs
   * const businessConfig = await prisma.businessConfig.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many BusinessConfigs and only return the `id`
   * const businessConfigWithIdOnly = await prisma.businessConfig.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BusinessConfigCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BusinessConfigCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BusinessConfigPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a BusinessConfig.
   * @param {BusinessConfigDeleteArgs} args - Arguments to delete one BusinessConfig.
   * @example
   * // Delete one BusinessConfig
   * const BusinessConfig = await prisma.businessConfig.delete({
   *   where: {
   *     // ... filter to delete one BusinessConfig
   *   }
   * })
   * 
   */
  delete<T extends BusinessConfigDeleteArgs>(args: Prisma.SelectSubset<T, BusinessConfigDeleteArgs<ExtArgs>>): Prisma.Prisma__BusinessConfigClient<runtime.Types.Result.GetResult<Prisma.$BusinessConfigPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one BusinessConfig.
   * @param {BusinessConfigUpdateArgs} args - Arguments to update one BusinessConfig.
   * @example
   * // Update one BusinessConfig
   * const businessConfig = await prisma.businessConfig.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BusinessConfigUpdateArgs>(args: Prisma.SelectSubset<T, BusinessConfigUpdateArgs<ExtArgs>>): Prisma.Prisma__BusinessConfigClient<runtime.Types.Result.GetResult<Prisma.$BusinessConfigPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more BusinessConfigs.
   * @param {BusinessConfigDeleteManyArgs} args - Arguments to filter BusinessConfigs to delete.
   * @example
   * // Delete a few BusinessConfigs
   * const { count } = await prisma.businessConfig.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BusinessConfigDeleteManyArgs>(args?: Prisma.SelectSubset<T, BusinessConfigDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BusinessConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BusinessConfigUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many BusinessConfigs
   * const businessConfig = await prisma.businessConfig.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BusinessConfigUpdateManyArgs>(args: Prisma.SelectSubset<T, BusinessConfigUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more BusinessConfigs and returns the data updated in the database.
   * @param {BusinessConfigUpdateManyAndReturnArgs} args - Arguments to update many BusinessConfigs.
   * @example
   * // Update many BusinessConfigs
   * const businessConfig = await prisma.businessConfig.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more BusinessConfigs and only return the `id`
   * const businessConfigWithIdOnly = await prisma.businessConfig.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BusinessConfigUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BusinessConfigUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BusinessConfigPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one BusinessConfig.
   * @param {BusinessConfigUpsertArgs} args - Arguments to update or create a BusinessConfig.
   * @example
   * // Update or create a BusinessConfig
   * const businessConfig = await prisma.businessConfig.upsert({
   *   create: {
   *     // ... data to create a BusinessConfig
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the BusinessConfig we want to update
   *   }
   * })
   */
  upsert<T extends BusinessConfigUpsertArgs>(args: Prisma.SelectSubset<T, BusinessConfigUpsertArgs<ExtArgs>>): Prisma.Prisma__BusinessConfigClient<runtime.Types.Result.GetResult<Prisma.$BusinessConfigPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of BusinessConfigs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BusinessConfigCountArgs} args - Arguments to filter BusinessConfigs to count.
   * @example
   * // Count the number of BusinessConfigs
   * const count = await prisma.businessConfig.count({
   *   where: {
   *     // ... the filter for the BusinessConfigs we want to count
   *   }
   * })
  **/
  count<T extends BusinessConfigCountArgs>(
    args?: Prisma.Subset<T, BusinessConfigCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BusinessConfigCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a BusinessConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BusinessConfigAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BusinessConfigAggregateArgs>(args: Prisma.Subset<T, BusinessConfigAggregateArgs>): Prisma.PrismaPromise<GetBusinessConfigAggregateType<T>>

  /**
   * Group by BusinessConfig.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BusinessConfigGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BusinessConfigGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BusinessConfigGroupByArgs['orderBy'] }
      : { orderBy?: BusinessConfigGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BusinessConfigGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBusinessConfigGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the BusinessConfig model
 */
readonly fields: BusinessConfigFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for BusinessConfig.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BusinessConfigClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the BusinessConfig model
 */
export interface BusinessConfigFieldRefs {
  readonly id: Prisma.FieldRef<"BusinessConfig", 'String'>
  readonly key: Prisma.FieldRef<"BusinessConfig", 'String'>
  readonly value: Prisma.FieldRef<"BusinessConfig", 'String'>
}
    

// Custom InputTypes
/**
 * BusinessConfig findUnique
 */
export type BusinessConfigFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BusinessConfig
   */
  select?: Prisma.BusinessConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BusinessConfig
   */
  omit?: Prisma.BusinessConfigOmit<ExtArgs> | null
  /**
   * Filter, which BusinessConfig to fetch.
   */
  where: Prisma.BusinessConfigWhereUniqueInput
}

/**
 * BusinessConfig findUniqueOrThrow
 */
export type BusinessConfigFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BusinessConfig
   */
  select?: Prisma.BusinessConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BusinessConfig
   */
  omit?: Prisma.BusinessConfigOmit<ExtArgs> | null
  /**
   * Filter, which BusinessConfig to fetch.
   */
  where: Prisma.BusinessConfigWhereUniqueInput
}

/**
 * BusinessConfig findFirst
 */
export type BusinessConfigFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BusinessConfig
   */
  select?: Prisma.BusinessConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BusinessConfig
   */
  omit?: Prisma.BusinessConfigOmit<ExtArgs> | null
  /**
   * Filter, which BusinessConfig to fetch.
   */
  where?: Prisma.BusinessConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BusinessConfigs to fetch.
   */
  orderBy?: Prisma.BusinessConfigOrderByWithRelationInput | Prisma.BusinessConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BusinessConfigs.
   */
  cursor?: Prisma.BusinessConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BusinessConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BusinessConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BusinessConfigs.
   */
  distinct?: Prisma.BusinessConfigScalarFieldEnum | Prisma.BusinessConfigScalarFieldEnum[]
}

/**
 * BusinessConfig findFirstOrThrow
 */
export type BusinessConfigFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BusinessConfig
   */
  select?: Prisma.BusinessConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BusinessConfig
   */
  omit?: Prisma.BusinessConfigOmit<ExtArgs> | null
  /**
   * Filter, which BusinessConfig to fetch.
   */
  where?: Prisma.BusinessConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BusinessConfigs to fetch.
   */
  orderBy?: Prisma.BusinessConfigOrderByWithRelationInput | Prisma.BusinessConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for BusinessConfigs.
   */
  cursor?: Prisma.BusinessConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BusinessConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BusinessConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BusinessConfigs.
   */
  distinct?: Prisma.BusinessConfigScalarFieldEnum | Prisma.BusinessConfigScalarFieldEnum[]
}

/**
 * BusinessConfig findMany
 */
export type BusinessConfigFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BusinessConfig
   */
  select?: Prisma.BusinessConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BusinessConfig
   */
  omit?: Prisma.BusinessConfigOmit<ExtArgs> | null
  /**
   * Filter, which BusinessConfigs to fetch.
   */
  where?: Prisma.BusinessConfigWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of BusinessConfigs to fetch.
   */
  orderBy?: Prisma.BusinessConfigOrderByWithRelationInput | Prisma.BusinessConfigOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing BusinessConfigs.
   */
  cursor?: Prisma.BusinessConfigWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` BusinessConfigs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` BusinessConfigs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of BusinessConfigs.
   */
  distinct?: Prisma.BusinessConfigScalarFieldEnum | Prisma.BusinessConfigScalarFieldEnum[]
}

/**
 * BusinessConfig create
 */
export type BusinessConfigCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BusinessConfig
   */
  select?: Prisma.BusinessConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BusinessConfig
   */
  omit?: Prisma.BusinessConfigOmit<ExtArgs> | null
  /**
   * The data needed to create a BusinessConfig.
   */
  data: Prisma.XOR<Prisma.BusinessConfigCreateInput, Prisma.BusinessConfigUncheckedCreateInput>
}

/**
 * BusinessConfig createMany
 */
export type BusinessConfigCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many BusinessConfigs.
   */
  data: Prisma.BusinessConfigCreateManyInput | Prisma.BusinessConfigCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BusinessConfig createManyAndReturn
 */
export type BusinessConfigCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BusinessConfig
   */
  select?: Prisma.BusinessConfigSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BusinessConfig
   */
  omit?: Prisma.BusinessConfigOmit<ExtArgs> | null
  /**
   * The data used to create many BusinessConfigs.
   */
  data: Prisma.BusinessConfigCreateManyInput | Prisma.BusinessConfigCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * BusinessConfig update
 */
export type BusinessConfigUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BusinessConfig
   */
  select?: Prisma.BusinessConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BusinessConfig
   */
  omit?: Prisma.BusinessConfigOmit<ExtArgs> | null
  /**
   * The data needed to update a BusinessConfig.
   */
  data: Prisma.XOR<Prisma.BusinessConfigUpdateInput, Prisma.BusinessConfigUncheckedUpdateInput>
  /**
   * Choose, which BusinessConfig to update.
   */
  where: Prisma.BusinessConfigWhereUniqueInput
}

/**
 * BusinessConfig updateMany
 */
export type BusinessConfigUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update BusinessConfigs.
   */
  data: Prisma.XOR<Prisma.BusinessConfigUpdateManyMutationInput, Prisma.BusinessConfigUncheckedUpdateManyInput>
  /**
   * Filter which BusinessConfigs to update
   */
  where?: Prisma.BusinessConfigWhereInput
  /**
   * Limit how many BusinessConfigs to update.
   */
  limit?: number
}

/**
 * BusinessConfig updateManyAndReturn
 */
export type BusinessConfigUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BusinessConfig
   */
  select?: Prisma.BusinessConfigSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the BusinessConfig
   */
  omit?: Prisma.BusinessConfigOmit<ExtArgs> | null
  /**
   * The data used to update BusinessConfigs.
   */
  data: Prisma.XOR<Prisma.BusinessConfigUpdateManyMutationInput, Prisma.BusinessConfigUncheckedUpdateManyInput>
  /**
   * Filter which BusinessConfigs to update
   */
  where?: Prisma.BusinessConfigWhereInput
  /**
   * Limit how many BusinessConfigs to update.
   */
  limit?: number
}

/**
 * BusinessConfig upsert
 */
export type BusinessConfigUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BusinessConfig
   */
  select?: Prisma.BusinessConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BusinessConfig
   */
  omit?: Prisma.BusinessConfigOmit<ExtArgs> | null
  /**
   * The filter to search for the BusinessConfig to update in case it exists.
   */
  where: Prisma.BusinessConfigWhereUniqueInput
  /**
   * In case the BusinessConfig found by the `where` argument doesn't exist, create a new BusinessConfig with this data.
   */
  create: Prisma.XOR<Prisma.BusinessConfigCreateInput, Prisma.BusinessConfigUncheckedCreateInput>
  /**
   * In case the BusinessConfig was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BusinessConfigUpdateInput, Prisma.BusinessConfigUncheckedUpdateInput>
}

/**
 * BusinessConfig delete
 */
export type BusinessConfigDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BusinessConfig
   */
  select?: Prisma.BusinessConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BusinessConfig
   */
  omit?: Prisma.BusinessConfigOmit<ExtArgs> | null
  /**
   * Filter which BusinessConfig to delete.
   */
  where: Prisma.BusinessConfigWhereUniqueInput
}

/**
 * BusinessConfig deleteMany
 */
export type BusinessConfigDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which BusinessConfigs to delete
   */
  where?: Prisma.BusinessConfigWhereInput
  /**
   * Limit how many BusinessConfigs to delete.
   */
  limit?: number
}

/**
 * BusinessConfig without action
 */
export type BusinessConfigDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BusinessConfig
   */
  select?: Prisma.BusinessConfigSelect<ExtArgs> | null
  /**
   * Omit specific fields from the BusinessConfig
   */
  omit?: Prisma.BusinessConfigOmit<ExtArgs> | null
}
