
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CustomerChannelIdentity` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CustomerChannelIdentity
 * 
 */
export type CustomerChannelIdentityModel = runtime.Types.Result.DefaultSelection<Prisma.$CustomerChannelIdentityPayload>

export type AggregateCustomerChannelIdentity = {
  _count: CustomerChannelIdentityCountAggregateOutputType | null
  _min: CustomerChannelIdentityMinAggregateOutputType | null
  _max: CustomerChannelIdentityMaxAggregateOutputType | null
}

export type CustomerChannelIdentityMinAggregateOutputType = {
  id: string | null
  customerId: string | null
  channel: $Enums.Channel | null
  channelCustomerId: string | null
  phone: string | null
  email: string | null
  createdAt: Date | null
}

export type CustomerChannelIdentityMaxAggregateOutputType = {
  id: string | null
  customerId: string | null
  channel: $Enums.Channel | null
  channelCustomerId: string | null
  phone: string | null
  email: string | null
  createdAt: Date | null
}

export type CustomerChannelIdentityCountAggregateOutputType = {
  id: number
  customerId: number
  channel: number
  channelCustomerId: number
  phone: number
  email: number
  createdAt: number
  _all: number
}


export type CustomerChannelIdentityMinAggregateInputType = {
  id?: true
  customerId?: true
  channel?: true
  channelCustomerId?: true
  phone?: true
  email?: true
  createdAt?: true
}

export type CustomerChannelIdentityMaxAggregateInputType = {
  id?: true
  customerId?: true
  channel?: true
  channelCustomerId?: true
  phone?: true
  email?: true
  createdAt?: true
}

export type CustomerChannelIdentityCountAggregateInputType = {
  id?: true
  customerId?: true
  channel?: true
  channelCustomerId?: true
  phone?: true
  email?: true
  createdAt?: true
  _all?: true
}

export type CustomerChannelIdentityAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CustomerChannelIdentity to aggregate.
   */
  where?: Prisma.CustomerChannelIdentityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomerChannelIdentities to fetch.
   */
  orderBy?: Prisma.CustomerChannelIdentityOrderByWithRelationInput | Prisma.CustomerChannelIdentityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CustomerChannelIdentityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomerChannelIdentities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomerChannelIdentities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CustomerChannelIdentities
  **/
  _count?: true | CustomerChannelIdentityCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CustomerChannelIdentityMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CustomerChannelIdentityMaxAggregateInputType
}

export type GetCustomerChannelIdentityAggregateType<T extends CustomerChannelIdentityAggregateArgs> = {
      [P in keyof T & keyof AggregateCustomerChannelIdentity]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCustomerChannelIdentity[P]>
    : Prisma.GetScalarType<T[P], AggregateCustomerChannelIdentity[P]>
}




export type CustomerChannelIdentityGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CustomerChannelIdentityWhereInput
  orderBy?: Prisma.CustomerChannelIdentityOrderByWithAggregationInput | Prisma.CustomerChannelIdentityOrderByWithAggregationInput[]
  by: Prisma.CustomerChannelIdentityScalarFieldEnum[] | Prisma.CustomerChannelIdentityScalarFieldEnum
  having?: Prisma.CustomerChannelIdentityScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CustomerChannelIdentityCountAggregateInputType | true
  _min?: CustomerChannelIdentityMinAggregateInputType
  _max?: CustomerChannelIdentityMaxAggregateInputType
}

export type CustomerChannelIdentityGroupByOutputType = {
  id: string
  customerId: string
  channel: $Enums.Channel
  channelCustomerId: string
  phone: string | null
  email: string | null
  createdAt: Date
  _count: CustomerChannelIdentityCountAggregateOutputType | null
  _min: CustomerChannelIdentityMinAggregateOutputType | null
  _max: CustomerChannelIdentityMaxAggregateOutputType | null
}

export type GetCustomerChannelIdentityGroupByPayload<T extends CustomerChannelIdentityGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CustomerChannelIdentityGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CustomerChannelIdentityGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CustomerChannelIdentityGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CustomerChannelIdentityGroupByOutputType[P]>
      }
    >
  >



export type CustomerChannelIdentityWhereInput = {
  AND?: Prisma.CustomerChannelIdentityWhereInput | Prisma.CustomerChannelIdentityWhereInput[]
  OR?: Prisma.CustomerChannelIdentityWhereInput[]
  NOT?: Prisma.CustomerChannelIdentityWhereInput | Prisma.CustomerChannelIdentityWhereInput[]
  id?: Prisma.StringFilter<"CustomerChannelIdentity"> | string
  customerId?: Prisma.StringFilter<"CustomerChannelIdentity"> | string
  channel?: Prisma.EnumChannelFilter<"CustomerChannelIdentity"> | $Enums.Channel
  channelCustomerId?: Prisma.StringFilter<"CustomerChannelIdentity"> | string
  phone?: Prisma.StringNullableFilter<"CustomerChannelIdentity"> | string | null
  email?: Prisma.StringNullableFilter<"CustomerChannelIdentity"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CustomerChannelIdentity"> | Date | string
  customer?: Prisma.XOR<Prisma.CustomerScalarRelationFilter, Prisma.CustomerWhereInput>
}

export type CustomerChannelIdentityOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  channelCustomerId?: Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  customer?: Prisma.CustomerOrderByWithRelationInput
}

export type CustomerChannelIdentityWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  channel_channelCustomerId?: Prisma.CustomerChannelIdentityChannelChannelCustomerIdCompoundUniqueInput
  AND?: Prisma.CustomerChannelIdentityWhereInput | Prisma.CustomerChannelIdentityWhereInput[]
  OR?: Prisma.CustomerChannelIdentityWhereInput[]
  NOT?: Prisma.CustomerChannelIdentityWhereInput | Prisma.CustomerChannelIdentityWhereInput[]
  customerId?: Prisma.StringFilter<"CustomerChannelIdentity"> | string
  channel?: Prisma.EnumChannelFilter<"CustomerChannelIdentity"> | $Enums.Channel
  channelCustomerId?: Prisma.StringFilter<"CustomerChannelIdentity"> | string
  phone?: Prisma.StringNullableFilter<"CustomerChannelIdentity"> | string | null
  email?: Prisma.StringNullableFilter<"CustomerChannelIdentity"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CustomerChannelIdentity"> | Date | string
  customer?: Prisma.XOR<Prisma.CustomerScalarRelationFilter, Prisma.CustomerWhereInput>
}, "id" | "channel_channelCustomerId">

export type CustomerChannelIdentityOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  channelCustomerId?: Prisma.SortOrder
  phone?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.CustomerChannelIdentityCountOrderByAggregateInput
  _max?: Prisma.CustomerChannelIdentityMaxOrderByAggregateInput
  _min?: Prisma.CustomerChannelIdentityMinOrderByAggregateInput
}

export type CustomerChannelIdentityScalarWhereWithAggregatesInput = {
  AND?: Prisma.CustomerChannelIdentityScalarWhereWithAggregatesInput | Prisma.CustomerChannelIdentityScalarWhereWithAggregatesInput[]
  OR?: Prisma.CustomerChannelIdentityScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CustomerChannelIdentityScalarWhereWithAggregatesInput | Prisma.CustomerChannelIdentityScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CustomerChannelIdentity"> | string
  customerId?: Prisma.StringWithAggregatesFilter<"CustomerChannelIdentity"> | string
  channel?: Prisma.EnumChannelWithAggregatesFilter<"CustomerChannelIdentity"> | $Enums.Channel
  channelCustomerId?: Prisma.StringWithAggregatesFilter<"CustomerChannelIdentity"> | string
  phone?: Prisma.StringNullableWithAggregatesFilter<"CustomerChannelIdentity"> | string | null
  email?: Prisma.StringNullableWithAggregatesFilter<"CustomerChannelIdentity"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CustomerChannelIdentity"> | Date | string
}

export type CustomerChannelIdentityCreateInput = {
  id?: string
  channel: $Enums.Channel
  channelCustomerId: string
  phone?: string | null
  email?: string | null
  createdAt?: Date | string
  customer: Prisma.CustomerCreateNestedOneWithoutChannelIdentitiesInput
}

export type CustomerChannelIdentityUncheckedCreateInput = {
  id?: string
  customerId: string
  channel: $Enums.Channel
  channelCustomerId: string
  phone?: string | null
  email?: string | null
  createdAt?: Date | string
}

export type CustomerChannelIdentityUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  channelCustomerId?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  customer?: Prisma.CustomerUpdateOneRequiredWithoutChannelIdentitiesNestedInput
}

export type CustomerChannelIdentityUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  channelCustomerId?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerChannelIdentityCreateManyInput = {
  id?: string
  customerId: string
  channel: $Enums.Channel
  channelCustomerId: string
  phone?: string | null
  email?: string | null
  createdAt?: Date | string
}

export type CustomerChannelIdentityUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  channelCustomerId?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerChannelIdentityUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  channelCustomerId?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerChannelIdentityListRelationFilter = {
  every?: Prisma.CustomerChannelIdentityWhereInput
  some?: Prisma.CustomerChannelIdentityWhereInput
  none?: Prisma.CustomerChannelIdentityWhereInput
}

export type CustomerChannelIdentityOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CustomerChannelIdentityChannelChannelCustomerIdCompoundUniqueInput = {
  channel: $Enums.Channel
  channelCustomerId: string
}

export type CustomerChannelIdentityCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  channelCustomerId?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CustomerChannelIdentityMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  channelCustomerId?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CustomerChannelIdentityMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  channel?: Prisma.SortOrder
  channelCustomerId?: Prisma.SortOrder
  phone?: Prisma.SortOrder
  email?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type CustomerChannelIdentityCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.CustomerChannelIdentityCreateWithoutCustomerInput, Prisma.CustomerChannelIdentityUncheckedCreateWithoutCustomerInput> | Prisma.CustomerChannelIdentityCreateWithoutCustomerInput[] | Prisma.CustomerChannelIdentityUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.CustomerChannelIdentityCreateOrConnectWithoutCustomerInput | Prisma.CustomerChannelIdentityCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.CustomerChannelIdentityCreateManyCustomerInputEnvelope
  connect?: Prisma.CustomerChannelIdentityWhereUniqueInput | Prisma.CustomerChannelIdentityWhereUniqueInput[]
}

export type CustomerChannelIdentityUncheckedCreateNestedManyWithoutCustomerInput = {
  create?: Prisma.XOR<Prisma.CustomerChannelIdentityCreateWithoutCustomerInput, Prisma.CustomerChannelIdentityUncheckedCreateWithoutCustomerInput> | Prisma.CustomerChannelIdentityCreateWithoutCustomerInput[] | Prisma.CustomerChannelIdentityUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.CustomerChannelIdentityCreateOrConnectWithoutCustomerInput | Prisma.CustomerChannelIdentityCreateOrConnectWithoutCustomerInput[]
  createMany?: Prisma.CustomerChannelIdentityCreateManyCustomerInputEnvelope
  connect?: Prisma.CustomerChannelIdentityWhereUniqueInput | Prisma.CustomerChannelIdentityWhereUniqueInput[]
}

export type CustomerChannelIdentityUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerChannelIdentityCreateWithoutCustomerInput, Prisma.CustomerChannelIdentityUncheckedCreateWithoutCustomerInput> | Prisma.CustomerChannelIdentityCreateWithoutCustomerInput[] | Prisma.CustomerChannelIdentityUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.CustomerChannelIdentityCreateOrConnectWithoutCustomerInput | Prisma.CustomerChannelIdentityCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.CustomerChannelIdentityUpsertWithWhereUniqueWithoutCustomerInput | Prisma.CustomerChannelIdentityUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.CustomerChannelIdentityCreateManyCustomerInputEnvelope
  set?: Prisma.CustomerChannelIdentityWhereUniqueInput | Prisma.CustomerChannelIdentityWhereUniqueInput[]
  disconnect?: Prisma.CustomerChannelIdentityWhereUniqueInput | Prisma.CustomerChannelIdentityWhereUniqueInput[]
  delete?: Prisma.CustomerChannelIdentityWhereUniqueInput | Prisma.CustomerChannelIdentityWhereUniqueInput[]
  connect?: Prisma.CustomerChannelIdentityWhereUniqueInput | Prisma.CustomerChannelIdentityWhereUniqueInput[]
  update?: Prisma.CustomerChannelIdentityUpdateWithWhereUniqueWithoutCustomerInput | Prisma.CustomerChannelIdentityUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.CustomerChannelIdentityUpdateManyWithWhereWithoutCustomerInput | Prisma.CustomerChannelIdentityUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.CustomerChannelIdentityScalarWhereInput | Prisma.CustomerChannelIdentityScalarWhereInput[]
}

export type CustomerChannelIdentityUncheckedUpdateManyWithoutCustomerNestedInput = {
  create?: Prisma.XOR<Prisma.CustomerChannelIdentityCreateWithoutCustomerInput, Prisma.CustomerChannelIdentityUncheckedCreateWithoutCustomerInput> | Prisma.CustomerChannelIdentityCreateWithoutCustomerInput[] | Prisma.CustomerChannelIdentityUncheckedCreateWithoutCustomerInput[]
  connectOrCreate?: Prisma.CustomerChannelIdentityCreateOrConnectWithoutCustomerInput | Prisma.CustomerChannelIdentityCreateOrConnectWithoutCustomerInput[]
  upsert?: Prisma.CustomerChannelIdentityUpsertWithWhereUniqueWithoutCustomerInput | Prisma.CustomerChannelIdentityUpsertWithWhereUniqueWithoutCustomerInput[]
  createMany?: Prisma.CustomerChannelIdentityCreateManyCustomerInputEnvelope
  set?: Prisma.CustomerChannelIdentityWhereUniqueInput | Prisma.CustomerChannelIdentityWhereUniqueInput[]
  disconnect?: Prisma.CustomerChannelIdentityWhereUniqueInput | Prisma.CustomerChannelIdentityWhereUniqueInput[]
  delete?: Prisma.CustomerChannelIdentityWhereUniqueInput | Prisma.CustomerChannelIdentityWhereUniqueInput[]
  connect?: Prisma.CustomerChannelIdentityWhereUniqueInput | Prisma.CustomerChannelIdentityWhereUniqueInput[]
  update?: Prisma.CustomerChannelIdentityUpdateWithWhereUniqueWithoutCustomerInput | Prisma.CustomerChannelIdentityUpdateWithWhereUniqueWithoutCustomerInput[]
  updateMany?: Prisma.CustomerChannelIdentityUpdateManyWithWhereWithoutCustomerInput | Prisma.CustomerChannelIdentityUpdateManyWithWhereWithoutCustomerInput[]
  deleteMany?: Prisma.CustomerChannelIdentityScalarWhereInput | Prisma.CustomerChannelIdentityScalarWhereInput[]
}

export type CustomerChannelIdentityCreateWithoutCustomerInput = {
  id?: string
  channel: $Enums.Channel
  channelCustomerId: string
  phone?: string | null
  email?: string | null
  createdAt?: Date | string
}

export type CustomerChannelIdentityUncheckedCreateWithoutCustomerInput = {
  id?: string
  channel: $Enums.Channel
  channelCustomerId: string
  phone?: string | null
  email?: string | null
  createdAt?: Date | string
}

export type CustomerChannelIdentityCreateOrConnectWithoutCustomerInput = {
  where: Prisma.CustomerChannelIdentityWhereUniqueInput
  create: Prisma.XOR<Prisma.CustomerChannelIdentityCreateWithoutCustomerInput, Prisma.CustomerChannelIdentityUncheckedCreateWithoutCustomerInput>
}

export type CustomerChannelIdentityCreateManyCustomerInputEnvelope = {
  data: Prisma.CustomerChannelIdentityCreateManyCustomerInput | Prisma.CustomerChannelIdentityCreateManyCustomerInput[]
  skipDuplicates?: boolean
}

export type CustomerChannelIdentityUpsertWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.CustomerChannelIdentityWhereUniqueInput
  update: Prisma.XOR<Prisma.CustomerChannelIdentityUpdateWithoutCustomerInput, Prisma.CustomerChannelIdentityUncheckedUpdateWithoutCustomerInput>
  create: Prisma.XOR<Prisma.CustomerChannelIdentityCreateWithoutCustomerInput, Prisma.CustomerChannelIdentityUncheckedCreateWithoutCustomerInput>
}

export type CustomerChannelIdentityUpdateWithWhereUniqueWithoutCustomerInput = {
  where: Prisma.CustomerChannelIdentityWhereUniqueInput
  data: Prisma.XOR<Prisma.CustomerChannelIdentityUpdateWithoutCustomerInput, Prisma.CustomerChannelIdentityUncheckedUpdateWithoutCustomerInput>
}

export type CustomerChannelIdentityUpdateManyWithWhereWithoutCustomerInput = {
  where: Prisma.CustomerChannelIdentityScalarWhereInput
  data: Prisma.XOR<Prisma.CustomerChannelIdentityUpdateManyMutationInput, Prisma.CustomerChannelIdentityUncheckedUpdateManyWithoutCustomerInput>
}

export type CustomerChannelIdentityScalarWhereInput = {
  AND?: Prisma.CustomerChannelIdentityScalarWhereInput | Prisma.CustomerChannelIdentityScalarWhereInput[]
  OR?: Prisma.CustomerChannelIdentityScalarWhereInput[]
  NOT?: Prisma.CustomerChannelIdentityScalarWhereInput | Prisma.CustomerChannelIdentityScalarWhereInput[]
  id?: Prisma.StringFilter<"CustomerChannelIdentity"> | string
  customerId?: Prisma.StringFilter<"CustomerChannelIdentity"> | string
  channel?: Prisma.EnumChannelFilter<"CustomerChannelIdentity"> | $Enums.Channel
  channelCustomerId?: Prisma.StringFilter<"CustomerChannelIdentity"> | string
  phone?: Prisma.StringNullableFilter<"CustomerChannelIdentity"> | string | null
  email?: Prisma.StringNullableFilter<"CustomerChannelIdentity"> | string | null
  createdAt?: Prisma.DateTimeFilter<"CustomerChannelIdentity"> | Date | string
}

export type CustomerChannelIdentityCreateManyCustomerInput = {
  id?: string
  channel: $Enums.Channel
  channelCustomerId: string
  phone?: string | null
  email?: string | null
  createdAt?: Date | string
}

export type CustomerChannelIdentityUpdateWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  channelCustomerId?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerChannelIdentityUncheckedUpdateWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  channelCustomerId?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CustomerChannelIdentityUncheckedUpdateManyWithoutCustomerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  channel?: Prisma.EnumChannelFieldUpdateOperationsInput | $Enums.Channel
  channelCustomerId?: Prisma.StringFieldUpdateOperationsInput | string
  phone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CustomerChannelIdentitySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  customerId?: boolean
  channel?: boolean
  channelCustomerId?: boolean
  phone?: boolean
  email?: boolean
  createdAt?: boolean
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customerChannelIdentity"]>

export type CustomerChannelIdentitySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  customerId?: boolean
  channel?: boolean
  channelCustomerId?: boolean
  phone?: boolean
  email?: boolean
  createdAt?: boolean
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customerChannelIdentity"]>

export type CustomerChannelIdentitySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  customerId?: boolean
  channel?: boolean
  channelCustomerId?: boolean
  phone?: boolean
  email?: boolean
  createdAt?: boolean
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
}, ExtArgs["result"]["customerChannelIdentity"]>

export type CustomerChannelIdentitySelectScalar = {
  id?: boolean
  customerId?: boolean
  channel?: boolean
  channelCustomerId?: boolean
  phone?: boolean
  email?: boolean
  createdAt?: boolean
}

export type CustomerChannelIdentityOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "customerId" | "channel" | "channelCustomerId" | "phone" | "email" | "createdAt", ExtArgs["result"]["customerChannelIdentity"]>
export type CustomerChannelIdentityInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
}
export type CustomerChannelIdentityIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
}
export type CustomerChannelIdentityIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  customer?: boolean | Prisma.CustomerDefaultArgs<ExtArgs>
}

export type $CustomerChannelIdentityPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CustomerChannelIdentity"
  objects: {
    customer: Prisma.$CustomerPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    customerId: string
    channel: $Enums.Channel
    channelCustomerId: string
    phone: string | null
    email: string | null
    createdAt: Date
  }, ExtArgs["result"]["customerChannelIdentity"]>
  composites: {}
}

export type CustomerChannelIdentityGetPayload<S extends boolean | null | undefined | CustomerChannelIdentityDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CustomerChannelIdentityPayload, S>

export type CustomerChannelIdentityCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CustomerChannelIdentityFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CustomerChannelIdentityCountAggregateInputType | true
  }

export interface CustomerChannelIdentityDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CustomerChannelIdentity'], meta: { name: 'CustomerChannelIdentity' } }
  /**
   * Find zero or one CustomerChannelIdentity that matches the filter.
   * @param {CustomerChannelIdentityFindUniqueArgs} args - Arguments to find a CustomerChannelIdentity
   * @example
   * // Get one CustomerChannelIdentity
   * const customerChannelIdentity = await prisma.customerChannelIdentity.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CustomerChannelIdentityFindUniqueArgs>(args: Prisma.SelectSubset<T, CustomerChannelIdentityFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CustomerChannelIdentityClient<runtime.Types.Result.GetResult<Prisma.$CustomerChannelIdentityPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CustomerChannelIdentity that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CustomerChannelIdentityFindUniqueOrThrowArgs} args - Arguments to find a CustomerChannelIdentity
   * @example
   * // Get one CustomerChannelIdentity
   * const customerChannelIdentity = await prisma.customerChannelIdentity.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CustomerChannelIdentityFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CustomerChannelIdentityFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomerChannelIdentityClient<runtime.Types.Result.GetResult<Prisma.$CustomerChannelIdentityPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CustomerChannelIdentity that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerChannelIdentityFindFirstArgs} args - Arguments to find a CustomerChannelIdentity
   * @example
   * // Get one CustomerChannelIdentity
   * const customerChannelIdentity = await prisma.customerChannelIdentity.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CustomerChannelIdentityFindFirstArgs>(args?: Prisma.SelectSubset<T, CustomerChannelIdentityFindFirstArgs<ExtArgs>>): Prisma.Prisma__CustomerChannelIdentityClient<runtime.Types.Result.GetResult<Prisma.$CustomerChannelIdentityPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CustomerChannelIdentity that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerChannelIdentityFindFirstOrThrowArgs} args - Arguments to find a CustomerChannelIdentity
   * @example
   * // Get one CustomerChannelIdentity
   * const customerChannelIdentity = await prisma.customerChannelIdentity.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CustomerChannelIdentityFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CustomerChannelIdentityFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CustomerChannelIdentityClient<runtime.Types.Result.GetResult<Prisma.$CustomerChannelIdentityPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CustomerChannelIdentities that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerChannelIdentityFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CustomerChannelIdentities
   * const customerChannelIdentities = await prisma.customerChannelIdentity.findMany()
   * 
   * // Get first 10 CustomerChannelIdentities
   * const customerChannelIdentities = await prisma.customerChannelIdentity.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const customerChannelIdentityWithIdOnly = await prisma.customerChannelIdentity.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CustomerChannelIdentityFindManyArgs>(args?: Prisma.SelectSubset<T, CustomerChannelIdentityFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomerChannelIdentityPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CustomerChannelIdentity.
   * @param {CustomerChannelIdentityCreateArgs} args - Arguments to create a CustomerChannelIdentity.
   * @example
   * // Create one CustomerChannelIdentity
   * const CustomerChannelIdentity = await prisma.customerChannelIdentity.create({
   *   data: {
   *     // ... data to create a CustomerChannelIdentity
   *   }
   * })
   * 
   */
  create<T extends CustomerChannelIdentityCreateArgs>(args: Prisma.SelectSubset<T, CustomerChannelIdentityCreateArgs<ExtArgs>>): Prisma.Prisma__CustomerChannelIdentityClient<runtime.Types.Result.GetResult<Prisma.$CustomerChannelIdentityPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CustomerChannelIdentities.
   * @param {CustomerChannelIdentityCreateManyArgs} args - Arguments to create many CustomerChannelIdentities.
   * @example
   * // Create many CustomerChannelIdentities
   * const customerChannelIdentity = await prisma.customerChannelIdentity.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CustomerChannelIdentityCreateManyArgs>(args?: Prisma.SelectSubset<T, CustomerChannelIdentityCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CustomerChannelIdentities and returns the data saved in the database.
   * @param {CustomerChannelIdentityCreateManyAndReturnArgs} args - Arguments to create many CustomerChannelIdentities.
   * @example
   * // Create many CustomerChannelIdentities
   * const customerChannelIdentity = await prisma.customerChannelIdentity.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CustomerChannelIdentities and only return the `id`
   * const customerChannelIdentityWithIdOnly = await prisma.customerChannelIdentity.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CustomerChannelIdentityCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CustomerChannelIdentityCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomerChannelIdentityPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CustomerChannelIdentity.
   * @param {CustomerChannelIdentityDeleteArgs} args - Arguments to delete one CustomerChannelIdentity.
   * @example
   * // Delete one CustomerChannelIdentity
   * const CustomerChannelIdentity = await prisma.customerChannelIdentity.delete({
   *   where: {
   *     // ... filter to delete one CustomerChannelIdentity
   *   }
   * })
   * 
   */
  delete<T extends CustomerChannelIdentityDeleteArgs>(args: Prisma.SelectSubset<T, CustomerChannelIdentityDeleteArgs<ExtArgs>>): Prisma.Prisma__CustomerChannelIdentityClient<runtime.Types.Result.GetResult<Prisma.$CustomerChannelIdentityPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CustomerChannelIdentity.
   * @param {CustomerChannelIdentityUpdateArgs} args - Arguments to update one CustomerChannelIdentity.
   * @example
   * // Update one CustomerChannelIdentity
   * const customerChannelIdentity = await prisma.customerChannelIdentity.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CustomerChannelIdentityUpdateArgs>(args: Prisma.SelectSubset<T, CustomerChannelIdentityUpdateArgs<ExtArgs>>): Prisma.Prisma__CustomerChannelIdentityClient<runtime.Types.Result.GetResult<Prisma.$CustomerChannelIdentityPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CustomerChannelIdentities.
   * @param {CustomerChannelIdentityDeleteManyArgs} args - Arguments to filter CustomerChannelIdentities to delete.
   * @example
   * // Delete a few CustomerChannelIdentities
   * const { count } = await prisma.customerChannelIdentity.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CustomerChannelIdentityDeleteManyArgs>(args?: Prisma.SelectSubset<T, CustomerChannelIdentityDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CustomerChannelIdentities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerChannelIdentityUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CustomerChannelIdentities
   * const customerChannelIdentity = await prisma.customerChannelIdentity.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CustomerChannelIdentityUpdateManyArgs>(args: Prisma.SelectSubset<T, CustomerChannelIdentityUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CustomerChannelIdentities and returns the data updated in the database.
   * @param {CustomerChannelIdentityUpdateManyAndReturnArgs} args - Arguments to update many CustomerChannelIdentities.
   * @example
   * // Update many CustomerChannelIdentities
   * const customerChannelIdentity = await prisma.customerChannelIdentity.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CustomerChannelIdentities and only return the `id`
   * const customerChannelIdentityWithIdOnly = await prisma.customerChannelIdentity.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CustomerChannelIdentityUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CustomerChannelIdentityUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CustomerChannelIdentityPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CustomerChannelIdentity.
   * @param {CustomerChannelIdentityUpsertArgs} args - Arguments to update or create a CustomerChannelIdentity.
   * @example
   * // Update or create a CustomerChannelIdentity
   * const customerChannelIdentity = await prisma.customerChannelIdentity.upsert({
   *   create: {
   *     // ... data to create a CustomerChannelIdentity
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CustomerChannelIdentity we want to update
   *   }
   * })
   */
  upsert<T extends CustomerChannelIdentityUpsertArgs>(args: Prisma.SelectSubset<T, CustomerChannelIdentityUpsertArgs<ExtArgs>>): Prisma.Prisma__CustomerChannelIdentityClient<runtime.Types.Result.GetResult<Prisma.$CustomerChannelIdentityPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CustomerChannelIdentities.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerChannelIdentityCountArgs} args - Arguments to filter CustomerChannelIdentities to count.
   * @example
   * // Count the number of CustomerChannelIdentities
   * const count = await prisma.customerChannelIdentity.count({
   *   where: {
   *     // ... the filter for the CustomerChannelIdentities we want to count
   *   }
   * })
  **/
  count<T extends CustomerChannelIdentityCountArgs>(
    args?: Prisma.Subset<T, CustomerChannelIdentityCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CustomerChannelIdentityCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CustomerChannelIdentity.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerChannelIdentityAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CustomerChannelIdentityAggregateArgs>(args: Prisma.Subset<T, CustomerChannelIdentityAggregateArgs>): Prisma.PrismaPromise<GetCustomerChannelIdentityAggregateType<T>>

  /**
   * Group by CustomerChannelIdentity.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CustomerChannelIdentityGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CustomerChannelIdentityGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CustomerChannelIdentityGroupByArgs['orderBy'] }
      : { orderBy?: CustomerChannelIdentityGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CustomerChannelIdentityGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCustomerChannelIdentityGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CustomerChannelIdentity model
 */
readonly fields: CustomerChannelIdentityFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CustomerChannelIdentity.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CustomerChannelIdentityClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  customer<T extends Prisma.CustomerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CustomerDefaultArgs<ExtArgs>>): Prisma.Prisma__CustomerClient<runtime.Types.Result.GetResult<Prisma.$CustomerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CustomerChannelIdentity model
 */
export interface CustomerChannelIdentityFieldRefs {
  readonly id: Prisma.FieldRef<"CustomerChannelIdentity", 'String'>
  readonly customerId: Prisma.FieldRef<"CustomerChannelIdentity", 'String'>
  readonly channel: Prisma.FieldRef<"CustomerChannelIdentity", 'Channel'>
  readonly channelCustomerId: Prisma.FieldRef<"CustomerChannelIdentity", 'String'>
  readonly phone: Prisma.FieldRef<"CustomerChannelIdentity", 'String'>
  readonly email: Prisma.FieldRef<"CustomerChannelIdentity", 'String'>
  readonly createdAt: Prisma.FieldRef<"CustomerChannelIdentity", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CustomerChannelIdentity findUnique
 */
export type CustomerChannelIdentityFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerChannelIdentity
   */
  select?: Prisma.CustomerChannelIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerChannelIdentity
   */
  omit?: Prisma.CustomerChannelIdentityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerChannelIdentityInclude<ExtArgs> | null
  /**
   * Filter, which CustomerChannelIdentity to fetch.
   */
  where: Prisma.CustomerChannelIdentityWhereUniqueInput
}

/**
 * CustomerChannelIdentity findUniqueOrThrow
 */
export type CustomerChannelIdentityFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerChannelIdentity
   */
  select?: Prisma.CustomerChannelIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerChannelIdentity
   */
  omit?: Prisma.CustomerChannelIdentityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerChannelIdentityInclude<ExtArgs> | null
  /**
   * Filter, which CustomerChannelIdentity to fetch.
   */
  where: Prisma.CustomerChannelIdentityWhereUniqueInput
}

/**
 * CustomerChannelIdentity findFirst
 */
export type CustomerChannelIdentityFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerChannelIdentity
   */
  select?: Prisma.CustomerChannelIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerChannelIdentity
   */
  omit?: Prisma.CustomerChannelIdentityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerChannelIdentityInclude<ExtArgs> | null
  /**
   * Filter, which CustomerChannelIdentity to fetch.
   */
  where?: Prisma.CustomerChannelIdentityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomerChannelIdentities to fetch.
   */
  orderBy?: Prisma.CustomerChannelIdentityOrderByWithRelationInput | Prisma.CustomerChannelIdentityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CustomerChannelIdentities.
   */
  cursor?: Prisma.CustomerChannelIdentityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomerChannelIdentities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomerChannelIdentities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CustomerChannelIdentities.
   */
  distinct?: Prisma.CustomerChannelIdentityScalarFieldEnum | Prisma.CustomerChannelIdentityScalarFieldEnum[]
}

/**
 * CustomerChannelIdentity findFirstOrThrow
 */
export type CustomerChannelIdentityFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerChannelIdentity
   */
  select?: Prisma.CustomerChannelIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerChannelIdentity
   */
  omit?: Prisma.CustomerChannelIdentityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerChannelIdentityInclude<ExtArgs> | null
  /**
   * Filter, which CustomerChannelIdentity to fetch.
   */
  where?: Prisma.CustomerChannelIdentityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomerChannelIdentities to fetch.
   */
  orderBy?: Prisma.CustomerChannelIdentityOrderByWithRelationInput | Prisma.CustomerChannelIdentityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CustomerChannelIdentities.
   */
  cursor?: Prisma.CustomerChannelIdentityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomerChannelIdentities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomerChannelIdentities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CustomerChannelIdentities.
   */
  distinct?: Prisma.CustomerChannelIdentityScalarFieldEnum | Prisma.CustomerChannelIdentityScalarFieldEnum[]
}

/**
 * CustomerChannelIdentity findMany
 */
export type CustomerChannelIdentityFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerChannelIdentity
   */
  select?: Prisma.CustomerChannelIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerChannelIdentity
   */
  omit?: Prisma.CustomerChannelIdentityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerChannelIdentityInclude<ExtArgs> | null
  /**
   * Filter, which CustomerChannelIdentities to fetch.
   */
  where?: Prisma.CustomerChannelIdentityWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CustomerChannelIdentities to fetch.
   */
  orderBy?: Prisma.CustomerChannelIdentityOrderByWithRelationInput | Prisma.CustomerChannelIdentityOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CustomerChannelIdentities.
   */
  cursor?: Prisma.CustomerChannelIdentityWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CustomerChannelIdentities from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CustomerChannelIdentities.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CustomerChannelIdentities.
   */
  distinct?: Prisma.CustomerChannelIdentityScalarFieldEnum | Prisma.CustomerChannelIdentityScalarFieldEnum[]
}

/**
 * CustomerChannelIdentity create
 */
export type CustomerChannelIdentityCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerChannelIdentity
   */
  select?: Prisma.CustomerChannelIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerChannelIdentity
   */
  omit?: Prisma.CustomerChannelIdentityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerChannelIdentityInclude<ExtArgs> | null
  /**
   * The data needed to create a CustomerChannelIdentity.
   */
  data: Prisma.XOR<Prisma.CustomerChannelIdentityCreateInput, Prisma.CustomerChannelIdentityUncheckedCreateInput>
}

/**
 * CustomerChannelIdentity createMany
 */
export type CustomerChannelIdentityCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CustomerChannelIdentities.
   */
  data: Prisma.CustomerChannelIdentityCreateManyInput | Prisma.CustomerChannelIdentityCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CustomerChannelIdentity createManyAndReturn
 */
export type CustomerChannelIdentityCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerChannelIdentity
   */
  select?: Prisma.CustomerChannelIdentitySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerChannelIdentity
   */
  omit?: Prisma.CustomerChannelIdentityOmit<ExtArgs> | null
  /**
   * The data used to create many CustomerChannelIdentities.
   */
  data: Prisma.CustomerChannelIdentityCreateManyInput | Prisma.CustomerChannelIdentityCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerChannelIdentityIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CustomerChannelIdentity update
 */
export type CustomerChannelIdentityUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerChannelIdentity
   */
  select?: Prisma.CustomerChannelIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerChannelIdentity
   */
  omit?: Prisma.CustomerChannelIdentityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerChannelIdentityInclude<ExtArgs> | null
  /**
   * The data needed to update a CustomerChannelIdentity.
   */
  data: Prisma.XOR<Prisma.CustomerChannelIdentityUpdateInput, Prisma.CustomerChannelIdentityUncheckedUpdateInput>
  /**
   * Choose, which CustomerChannelIdentity to update.
   */
  where: Prisma.CustomerChannelIdentityWhereUniqueInput
}

/**
 * CustomerChannelIdentity updateMany
 */
export type CustomerChannelIdentityUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CustomerChannelIdentities.
   */
  data: Prisma.XOR<Prisma.CustomerChannelIdentityUpdateManyMutationInput, Prisma.CustomerChannelIdentityUncheckedUpdateManyInput>
  /**
   * Filter which CustomerChannelIdentities to update
   */
  where?: Prisma.CustomerChannelIdentityWhereInput
  /**
   * Limit how many CustomerChannelIdentities to update.
   */
  limit?: number
}

/**
 * CustomerChannelIdentity updateManyAndReturn
 */
export type CustomerChannelIdentityUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerChannelIdentity
   */
  select?: Prisma.CustomerChannelIdentitySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerChannelIdentity
   */
  omit?: Prisma.CustomerChannelIdentityOmit<ExtArgs> | null
  /**
   * The data used to update CustomerChannelIdentities.
   */
  data: Prisma.XOR<Prisma.CustomerChannelIdentityUpdateManyMutationInput, Prisma.CustomerChannelIdentityUncheckedUpdateManyInput>
  /**
   * Filter which CustomerChannelIdentities to update
   */
  where?: Prisma.CustomerChannelIdentityWhereInput
  /**
   * Limit how many CustomerChannelIdentities to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerChannelIdentityIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CustomerChannelIdentity upsert
 */
export type CustomerChannelIdentityUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerChannelIdentity
   */
  select?: Prisma.CustomerChannelIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerChannelIdentity
   */
  omit?: Prisma.CustomerChannelIdentityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerChannelIdentityInclude<ExtArgs> | null
  /**
   * The filter to search for the CustomerChannelIdentity to update in case it exists.
   */
  where: Prisma.CustomerChannelIdentityWhereUniqueInput
  /**
   * In case the CustomerChannelIdentity found by the `where` argument doesn't exist, create a new CustomerChannelIdentity with this data.
   */
  create: Prisma.XOR<Prisma.CustomerChannelIdentityCreateInput, Prisma.CustomerChannelIdentityUncheckedCreateInput>
  /**
   * In case the CustomerChannelIdentity was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CustomerChannelIdentityUpdateInput, Prisma.CustomerChannelIdentityUncheckedUpdateInput>
}

/**
 * CustomerChannelIdentity delete
 */
export type CustomerChannelIdentityDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerChannelIdentity
   */
  select?: Prisma.CustomerChannelIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerChannelIdentity
   */
  omit?: Prisma.CustomerChannelIdentityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerChannelIdentityInclude<ExtArgs> | null
  /**
   * Filter which CustomerChannelIdentity to delete.
   */
  where: Prisma.CustomerChannelIdentityWhereUniqueInput
}

/**
 * CustomerChannelIdentity deleteMany
 */
export type CustomerChannelIdentityDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CustomerChannelIdentities to delete
   */
  where?: Prisma.CustomerChannelIdentityWhereInput
  /**
   * Limit how many CustomerChannelIdentities to delete.
   */
  limit?: number
}

/**
 * CustomerChannelIdentity without action
 */
export type CustomerChannelIdentityDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CustomerChannelIdentity
   */
  select?: Prisma.CustomerChannelIdentitySelect<ExtArgs> | null
  /**
   * Omit specific fields from the CustomerChannelIdentity
   */
  omit?: Prisma.CustomerChannelIdentityOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CustomerChannelIdentityInclude<ExtArgs> | null
}
