
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Procurement` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Procurement
 * 
 */
export type ProcurementModel = runtime.Types.Result.DefaultSelection<Prisma.$ProcurementPayload>

export type AggregateProcurement = {
  _count: ProcurementCountAggregateOutputType | null
  _avg: ProcurementAvgAggregateOutputType | null
  _sum: ProcurementSumAggregateOutputType | null
  _min: ProcurementMinAggregateOutputType | null
  _max: ProcurementMaxAggregateOutputType | null
}

export type ProcurementAvgAggregateOutputType = {
  totalCost: runtime.Decimal | null
}

export type ProcurementSumAggregateOutputType = {
  totalCost: runtime.Decimal | null
}

export type ProcurementMinAggregateOutputType = {
  id: string | null
  poNumber: string | null
  supplierId: string | null
  status: $Enums.ProcurementStatus | null
  orderDate: Date | null
  receivedDate: Date | null
  notes: string | null
  totalCost: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProcurementMaxAggregateOutputType = {
  id: string | null
  poNumber: string | null
  supplierId: string | null
  status: $Enums.ProcurementStatus | null
  orderDate: Date | null
  receivedDate: Date | null
  notes: string | null
  totalCost: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProcurementCountAggregateOutputType = {
  id: number
  poNumber: number
  supplierId: number
  status: number
  orderDate: number
  receivedDate: number
  notes: number
  totalCost: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ProcurementAvgAggregateInputType = {
  totalCost?: true
}

export type ProcurementSumAggregateInputType = {
  totalCost?: true
}

export type ProcurementMinAggregateInputType = {
  id?: true
  poNumber?: true
  supplierId?: true
  status?: true
  orderDate?: true
  receivedDate?: true
  notes?: true
  totalCost?: true
  createdAt?: true
  updatedAt?: true
}

export type ProcurementMaxAggregateInputType = {
  id?: true
  poNumber?: true
  supplierId?: true
  status?: true
  orderDate?: true
  receivedDate?: true
  notes?: true
  totalCost?: true
  createdAt?: true
  updatedAt?: true
}

export type ProcurementCountAggregateInputType = {
  id?: true
  poNumber?: true
  supplierId?: true
  status?: true
  orderDate?: true
  receivedDate?: true
  notes?: true
  totalCost?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ProcurementAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Procurement to aggregate.
   */
  where?: Prisma.ProcurementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Procurements to fetch.
   */
  orderBy?: Prisma.ProcurementOrderByWithRelationInput | Prisma.ProcurementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProcurementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Procurements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Procurements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Procurements
  **/
  _count?: true | ProcurementCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProcurementAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProcurementSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProcurementMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProcurementMaxAggregateInputType
}

export type GetProcurementAggregateType<T extends ProcurementAggregateArgs> = {
      [P in keyof T & keyof AggregateProcurement]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProcurement[P]>
    : Prisma.GetScalarType<T[P], AggregateProcurement[P]>
}




export type ProcurementGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProcurementWhereInput
  orderBy?: Prisma.ProcurementOrderByWithAggregationInput | Prisma.ProcurementOrderByWithAggregationInput[]
  by: Prisma.ProcurementScalarFieldEnum[] | Prisma.ProcurementScalarFieldEnum
  having?: Prisma.ProcurementScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProcurementCountAggregateInputType | true
  _avg?: ProcurementAvgAggregateInputType
  _sum?: ProcurementSumAggregateInputType
  _min?: ProcurementMinAggregateInputType
  _max?: ProcurementMaxAggregateInputType
}

export type ProcurementGroupByOutputType = {
  id: string
  poNumber: string
  supplierId: string
  status: $Enums.ProcurementStatus
  orderDate: Date
  receivedDate: Date | null
  notes: string | null
  totalCost: runtime.Decimal
  createdAt: Date
  updatedAt: Date
  _count: ProcurementCountAggregateOutputType | null
  _avg: ProcurementAvgAggregateOutputType | null
  _sum: ProcurementSumAggregateOutputType | null
  _min: ProcurementMinAggregateOutputType | null
  _max: ProcurementMaxAggregateOutputType | null
}

export type GetProcurementGroupByPayload<T extends ProcurementGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProcurementGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProcurementGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProcurementGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProcurementGroupByOutputType[P]>
      }
    >
  >



export type ProcurementWhereInput = {
  AND?: Prisma.ProcurementWhereInput | Prisma.ProcurementWhereInput[]
  OR?: Prisma.ProcurementWhereInput[]
  NOT?: Prisma.ProcurementWhereInput | Prisma.ProcurementWhereInput[]
  id?: Prisma.StringFilter<"Procurement"> | string
  poNumber?: Prisma.StringFilter<"Procurement"> | string
  supplierId?: Prisma.StringFilter<"Procurement"> | string
  status?: Prisma.EnumProcurementStatusFilter<"Procurement"> | $Enums.ProcurementStatus
  orderDate?: Prisma.DateTimeFilter<"Procurement"> | Date | string
  receivedDate?: Prisma.DateTimeNullableFilter<"Procurement"> | Date | string | null
  notes?: Prisma.StringNullableFilter<"Procurement"> | string | null
  totalCost?: Prisma.DecimalFilter<"Procurement"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"Procurement"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Procurement"> | Date | string
  supplier?: Prisma.XOR<Prisma.SupplierScalarRelationFilter, Prisma.SupplierWhereInput>
  items?: Prisma.ProcurementItemListRelationFilter
}

export type ProcurementOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  poNumber?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  orderDate?: Prisma.SortOrder
  receivedDate?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  totalCost?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  supplier?: Prisma.SupplierOrderByWithRelationInput
  items?: Prisma.ProcurementItemOrderByRelationAggregateInput
}

export type ProcurementWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  poNumber?: string
  AND?: Prisma.ProcurementWhereInput | Prisma.ProcurementWhereInput[]
  OR?: Prisma.ProcurementWhereInput[]
  NOT?: Prisma.ProcurementWhereInput | Prisma.ProcurementWhereInput[]
  supplierId?: Prisma.StringFilter<"Procurement"> | string
  status?: Prisma.EnumProcurementStatusFilter<"Procurement"> | $Enums.ProcurementStatus
  orderDate?: Prisma.DateTimeFilter<"Procurement"> | Date | string
  receivedDate?: Prisma.DateTimeNullableFilter<"Procurement"> | Date | string | null
  notes?: Prisma.StringNullableFilter<"Procurement"> | string | null
  totalCost?: Prisma.DecimalFilter<"Procurement"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"Procurement"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Procurement"> | Date | string
  supplier?: Prisma.XOR<Prisma.SupplierScalarRelationFilter, Prisma.SupplierWhereInput>
  items?: Prisma.ProcurementItemListRelationFilter
}, "id" | "poNumber">

export type ProcurementOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  poNumber?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  orderDate?: Prisma.SortOrder
  receivedDate?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  totalCost?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProcurementCountOrderByAggregateInput
  _avg?: Prisma.ProcurementAvgOrderByAggregateInput
  _max?: Prisma.ProcurementMaxOrderByAggregateInput
  _min?: Prisma.ProcurementMinOrderByAggregateInput
  _sum?: Prisma.ProcurementSumOrderByAggregateInput
}

export type ProcurementScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProcurementScalarWhereWithAggregatesInput | Prisma.ProcurementScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProcurementScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProcurementScalarWhereWithAggregatesInput | Prisma.ProcurementScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Procurement"> | string
  poNumber?: Prisma.StringWithAggregatesFilter<"Procurement"> | string
  supplierId?: Prisma.StringWithAggregatesFilter<"Procurement"> | string
  status?: Prisma.EnumProcurementStatusWithAggregatesFilter<"Procurement"> | $Enums.ProcurementStatus
  orderDate?: Prisma.DateTimeWithAggregatesFilter<"Procurement"> | Date | string
  receivedDate?: Prisma.DateTimeNullableWithAggregatesFilter<"Procurement"> | Date | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"Procurement"> | string | null
  totalCost?: Prisma.DecimalWithAggregatesFilter<"Procurement"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Procurement"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Procurement"> | Date | string
}

export type ProcurementCreateInput = {
  id?: string
  poNumber: string
  status?: $Enums.ProcurementStatus
  orderDate?: Date | string
  receivedDate?: Date | string | null
  notes?: string | null
  totalCost: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  supplier: Prisma.SupplierCreateNestedOneWithoutProcurementsInput
  items?: Prisma.ProcurementItemCreateNestedManyWithoutProcurementInput
}

export type ProcurementUncheckedCreateInput = {
  id?: string
  poNumber: string
  supplierId: string
  status?: $Enums.ProcurementStatus
  orderDate?: Date | string
  receivedDate?: Date | string | null
  notes?: string | null
  totalCost: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  items?: Prisma.ProcurementItemUncheckedCreateNestedManyWithoutProcurementInput
}

export type ProcurementUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  poNumber?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProcurementStatusFieldUpdateOperationsInput | $Enums.ProcurementStatus
  orderDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  receivedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalCost?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  supplier?: Prisma.SupplierUpdateOneRequiredWithoutProcurementsNestedInput
  items?: Prisma.ProcurementItemUpdateManyWithoutProcurementNestedInput
}

export type ProcurementUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  poNumber?: Prisma.StringFieldUpdateOperationsInput | string
  supplierId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProcurementStatusFieldUpdateOperationsInput | $Enums.ProcurementStatus
  orderDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  receivedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalCost?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.ProcurementItemUncheckedUpdateManyWithoutProcurementNestedInput
}

export type ProcurementCreateManyInput = {
  id?: string
  poNumber: string
  supplierId: string
  status?: $Enums.ProcurementStatus
  orderDate?: Date | string
  receivedDate?: Date | string | null
  notes?: string | null
  totalCost: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProcurementUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  poNumber?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProcurementStatusFieldUpdateOperationsInput | $Enums.ProcurementStatus
  orderDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  receivedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalCost?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProcurementUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  poNumber?: Prisma.StringFieldUpdateOperationsInput | string
  supplierId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProcurementStatusFieldUpdateOperationsInput | $Enums.ProcurementStatus
  orderDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  receivedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalCost?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProcurementListRelationFilter = {
  every?: Prisma.ProcurementWhereInput
  some?: Prisma.ProcurementWhereInput
  none?: Prisma.ProcurementWhereInput
}

export type ProcurementOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProcurementCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  poNumber?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  orderDate?: Prisma.SortOrder
  receivedDate?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  totalCost?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProcurementAvgOrderByAggregateInput = {
  totalCost?: Prisma.SortOrder
}

export type ProcurementMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  poNumber?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  orderDate?: Prisma.SortOrder
  receivedDate?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  totalCost?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProcurementMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  poNumber?: Prisma.SortOrder
  supplierId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  orderDate?: Prisma.SortOrder
  receivedDate?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  totalCost?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProcurementSumOrderByAggregateInput = {
  totalCost?: Prisma.SortOrder
}

export type ProcurementScalarRelationFilter = {
  is?: Prisma.ProcurementWhereInput
  isNot?: Prisma.ProcurementWhereInput
}

export type ProcurementCreateNestedManyWithoutSupplierInput = {
  create?: Prisma.XOR<Prisma.ProcurementCreateWithoutSupplierInput, Prisma.ProcurementUncheckedCreateWithoutSupplierInput> | Prisma.ProcurementCreateWithoutSupplierInput[] | Prisma.ProcurementUncheckedCreateWithoutSupplierInput[]
  connectOrCreate?: Prisma.ProcurementCreateOrConnectWithoutSupplierInput | Prisma.ProcurementCreateOrConnectWithoutSupplierInput[]
  createMany?: Prisma.ProcurementCreateManySupplierInputEnvelope
  connect?: Prisma.ProcurementWhereUniqueInput | Prisma.ProcurementWhereUniqueInput[]
}

export type ProcurementUncheckedCreateNestedManyWithoutSupplierInput = {
  create?: Prisma.XOR<Prisma.ProcurementCreateWithoutSupplierInput, Prisma.ProcurementUncheckedCreateWithoutSupplierInput> | Prisma.ProcurementCreateWithoutSupplierInput[] | Prisma.ProcurementUncheckedCreateWithoutSupplierInput[]
  connectOrCreate?: Prisma.ProcurementCreateOrConnectWithoutSupplierInput | Prisma.ProcurementCreateOrConnectWithoutSupplierInput[]
  createMany?: Prisma.ProcurementCreateManySupplierInputEnvelope
  connect?: Prisma.ProcurementWhereUniqueInput | Prisma.ProcurementWhereUniqueInput[]
}

export type ProcurementUpdateManyWithoutSupplierNestedInput = {
  create?: Prisma.XOR<Prisma.ProcurementCreateWithoutSupplierInput, Prisma.ProcurementUncheckedCreateWithoutSupplierInput> | Prisma.ProcurementCreateWithoutSupplierInput[] | Prisma.ProcurementUncheckedCreateWithoutSupplierInput[]
  connectOrCreate?: Prisma.ProcurementCreateOrConnectWithoutSupplierInput | Prisma.ProcurementCreateOrConnectWithoutSupplierInput[]
  upsert?: Prisma.ProcurementUpsertWithWhereUniqueWithoutSupplierInput | Prisma.ProcurementUpsertWithWhereUniqueWithoutSupplierInput[]
  createMany?: Prisma.ProcurementCreateManySupplierInputEnvelope
  set?: Prisma.ProcurementWhereUniqueInput | Prisma.ProcurementWhereUniqueInput[]
  disconnect?: Prisma.ProcurementWhereUniqueInput | Prisma.ProcurementWhereUniqueInput[]
  delete?: Prisma.ProcurementWhereUniqueInput | Prisma.ProcurementWhereUniqueInput[]
  connect?: Prisma.ProcurementWhereUniqueInput | Prisma.ProcurementWhereUniqueInput[]
  update?: Prisma.ProcurementUpdateWithWhereUniqueWithoutSupplierInput | Prisma.ProcurementUpdateWithWhereUniqueWithoutSupplierInput[]
  updateMany?: Prisma.ProcurementUpdateManyWithWhereWithoutSupplierInput | Prisma.ProcurementUpdateManyWithWhereWithoutSupplierInput[]
  deleteMany?: Prisma.ProcurementScalarWhereInput | Prisma.ProcurementScalarWhereInput[]
}

export type ProcurementUncheckedUpdateManyWithoutSupplierNestedInput = {
  create?: Prisma.XOR<Prisma.ProcurementCreateWithoutSupplierInput, Prisma.ProcurementUncheckedCreateWithoutSupplierInput> | Prisma.ProcurementCreateWithoutSupplierInput[] | Prisma.ProcurementUncheckedCreateWithoutSupplierInput[]
  connectOrCreate?: Prisma.ProcurementCreateOrConnectWithoutSupplierInput | Prisma.ProcurementCreateOrConnectWithoutSupplierInput[]
  upsert?: Prisma.ProcurementUpsertWithWhereUniqueWithoutSupplierInput | Prisma.ProcurementUpsertWithWhereUniqueWithoutSupplierInput[]
  createMany?: Prisma.ProcurementCreateManySupplierInputEnvelope
  set?: Prisma.ProcurementWhereUniqueInput | Prisma.ProcurementWhereUniqueInput[]
  disconnect?: Prisma.ProcurementWhereUniqueInput | Prisma.ProcurementWhereUniqueInput[]
  delete?: Prisma.ProcurementWhereUniqueInput | Prisma.ProcurementWhereUniqueInput[]
  connect?: Prisma.ProcurementWhereUniqueInput | Prisma.ProcurementWhereUniqueInput[]
  update?: Prisma.ProcurementUpdateWithWhereUniqueWithoutSupplierInput | Prisma.ProcurementUpdateWithWhereUniqueWithoutSupplierInput[]
  updateMany?: Prisma.ProcurementUpdateManyWithWhereWithoutSupplierInput | Prisma.ProcurementUpdateManyWithWhereWithoutSupplierInput[]
  deleteMany?: Prisma.ProcurementScalarWhereInput | Prisma.ProcurementScalarWhereInput[]
}

export type EnumProcurementStatusFieldUpdateOperationsInput = {
  set?: $Enums.ProcurementStatus
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type ProcurementCreateNestedOneWithoutItemsInput = {
  create?: Prisma.XOR<Prisma.ProcurementCreateWithoutItemsInput, Prisma.ProcurementUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.ProcurementCreateOrConnectWithoutItemsInput
  connect?: Prisma.ProcurementWhereUniqueInput
}

export type ProcurementUpdateOneRequiredWithoutItemsNestedInput = {
  create?: Prisma.XOR<Prisma.ProcurementCreateWithoutItemsInput, Prisma.ProcurementUncheckedCreateWithoutItemsInput>
  connectOrCreate?: Prisma.ProcurementCreateOrConnectWithoutItemsInput
  upsert?: Prisma.ProcurementUpsertWithoutItemsInput
  connect?: Prisma.ProcurementWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ProcurementUpdateToOneWithWhereWithoutItemsInput, Prisma.ProcurementUpdateWithoutItemsInput>, Prisma.ProcurementUncheckedUpdateWithoutItemsInput>
}

export type ProcurementCreateWithoutSupplierInput = {
  id?: string
  poNumber: string
  status?: $Enums.ProcurementStatus
  orderDate?: Date | string
  receivedDate?: Date | string | null
  notes?: string | null
  totalCost: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  items?: Prisma.ProcurementItemCreateNestedManyWithoutProcurementInput
}

export type ProcurementUncheckedCreateWithoutSupplierInput = {
  id?: string
  poNumber: string
  status?: $Enums.ProcurementStatus
  orderDate?: Date | string
  receivedDate?: Date | string | null
  notes?: string | null
  totalCost: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  items?: Prisma.ProcurementItemUncheckedCreateNestedManyWithoutProcurementInput
}

export type ProcurementCreateOrConnectWithoutSupplierInput = {
  where: Prisma.ProcurementWhereUniqueInput
  create: Prisma.XOR<Prisma.ProcurementCreateWithoutSupplierInput, Prisma.ProcurementUncheckedCreateWithoutSupplierInput>
}

export type ProcurementCreateManySupplierInputEnvelope = {
  data: Prisma.ProcurementCreateManySupplierInput | Prisma.ProcurementCreateManySupplierInput[]
  skipDuplicates?: boolean
}

export type ProcurementUpsertWithWhereUniqueWithoutSupplierInput = {
  where: Prisma.ProcurementWhereUniqueInput
  update: Prisma.XOR<Prisma.ProcurementUpdateWithoutSupplierInput, Prisma.ProcurementUncheckedUpdateWithoutSupplierInput>
  create: Prisma.XOR<Prisma.ProcurementCreateWithoutSupplierInput, Prisma.ProcurementUncheckedCreateWithoutSupplierInput>
}

export type ProcurementUpdateWithWhereUniqueWithoutSupplierInput = {
  where: Prisma.ProcurementWhereUniqueInput
  data: Prisma.XOR<Prisma.ProcurementUpdateWithoutSupplierInput, Prisma.ProcurementUncheckedUpdateWithoutSupplierInput>
}

export type ProcurementUpdateManyWithWhereWithoutSupplierInput = {
  where: Prisma.ProcurementScalarWhereInput
  data: Prisma.XOR<Prisma.ProcurementUpdateManyMutationInput, Prisma.ProcurementUncheckedUpdateManyWithoutSupplierInput>
}

export type ProcurementScalarWhereInput = {
  AND?: Prisma.ProcurementScalarWhereInput | Prisma.ProcurementScalarWhereInput[]
  OR?: Prisma.ProcurementScalarWhereInput[]
  NOT?: Prisma.ProcurementScalarWhereInput | Prisma.ProcurementScalarWhereInput[]
  id?: Prisma.StringFilter<"Procurement"> | string
  poNumber?: Prisma.StringFilter<"Procurement"> | string
  supplierId?: Prisma.StringFilter<"Procurement"> | string
  status?: Prisma.EnumProcurementStatusFilter<"Procurement"> | $Enums.ProcurementStatus
  orderDate?: Prisma.DateTimeFilter<"Procurement"> | Date | string
  receivedDate?: Prisma.DateTimeNullableFilter<"Procurement"> | Date | string | null
  notes?: Prisma.StringNullableFilter<"Procurement"> | string | null
  totalCost?: Prisma.DecimalFilter<"Procurement"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"Procurement"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Procurement"> | Date | string
}

export type ProcurementCreateWithoutItemsInput = {
  id?: string
  poNumber: string
  status?: $Enums.ProcurementStatus
  orderDate?: Date | string
  receivedDate?: Date | string | null
  notes?: string | null
  totalCost: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  supplier: Prisma.SupplierCreateNestedOneWithoutProcurementsInput
}

export type ProcurementUncheckedCreateWithoutItemsInput = {
  id?: string
  poNumber: string
  supplierId: string
  status?: $Enums.ProcurementStatus
  orderDate?: Date | string
  receivedDate?: Date | string | null
  notes?: string | null
  totalCost: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProcurementCreateOrConnectWithoutItemsInput = {
  where: Prisma.ProcurementWhereUniqueInput
  create: Prisma.XOR<Prisma.ProcurementCreateWithoutItemsInput, Prisma.ProcurementUncheckedCreateWithoutItemsInput>
}

export type ProcurementUpsertWithoutItemsInput = {
  update: Prisma.XOR<Prisma.ProcurementUpdateWithoutItemsInput, Prisma.ProcurementUncheckedUpdateWithoutItemsInput>
  create: Prisma.XOR<Prisma.ProcurementCreateWithoutItemsInput, Prisma.ProcurementUncheckedCreateWithoutItemsInput>
  where?: Prisma.ProcurementWhereInput
}

export type ProcurementUpdateToOneWithWhereWithoutItemsInput = {
  where?: Prisma.ProcurementWhereInput
  data: Prisma.XOR<Prisma.ProcurementUpdateWithoutItemsInput, Prisma.ProcurementUncheckedUpdateWithoutItemsInput>
}

export type ProcurementUpdateWithoutItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  poNumber?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProcurementStatusFieldUpdateOperationsInput | $Enums.ProcurementStatus
  orderDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  receivedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalCost?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  supplier?: Prisma.SupplierUpdateOneRequiredWithoutProcurementsNestedInput
}

export type ProcurementUncheckedUpdateWithoutItemsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  poNumber?: Prisma.StringFieldUpdateOperationsInput | string
  supplierId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProcurementStatusFieldUpdateOperationsInput | $Enums.ProcurementStatus
  orderDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  receivedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalCost?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProcurementCreateManySupplierInput = {
  id?: string
  poNumber: string
  status?: $Enums.ProcurementStatus
  orderDate?: Date | string
  receivedDate?: Date | string | null
  notes?: string | null
  totalCost: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProcurementUpdateWithoutSupplierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  poNumber?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProcurementStatusFieldUpdateOperationsInput | $Enums.ProcurementStatus
  orderDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  receivedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalCost?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.ProcurementItemUpdateManyWithoutProcurementNestedInput
}

export type ProcurementUncheckedUpdateWithoutSupplierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  poNumber?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProcurementStatusFieldUpdateOperationsInput | $Enums.ProcurementStatus
  orderDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  receivedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalCost?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  items?: Prisma.ProcurementItemUncheckedUpdateManyWithoutProcurementNestedInput
}

export type ProcurementUncheckedUpdateManyWithoutSupplierInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  poNumber?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumProcurementStatusFieldUpdateOperationsInput | $Enums.ProcurementStatus
  orderDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  receivedDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  totalCost?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ProcurementCountOutputType
 */

export type ProcurementCountOutputType = {
  items: number
}

export type ProcurementCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  items?: boolean | ProcurementCountOutputTypeCountItemsArgs
}

/**
 * ProcurementCountOutputType without action
 */
export type ProcurementCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProcurementCountOutputType
   */
  select?: Prisma.ProcurementCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProcurementCountOutputType without action
 */
export type ProcurementCountOutputTypeCountItemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProcurementItemWhereInput
}


export type ProcurementSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  poNumber?: boolean
  supplierId?: boolean
  status?: boolean
  orderDate?: boolean
  receivedDate?: boolean
  notes?: boolean
  totalCost?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
  items?: boolean | Prisma.Procurement$itemsArgs<ExtArgs>
  _count?: boolean | Prisma.ProcurementCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["procurement"]>

export type ProcurementSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  poNumber?: boolean
  supplierId?: boolean
  status?: boolean
  orderDate?: boolean
  receivedDate?: boolean
  notes?: boolean
  totalCost?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
}, ExtArgs["result"]["procurement"]>

export type ProcurementSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  poNumber?: boolean
  supplierId?: boolean
  status?: boolean
  orderDate?: boolean
  receivedDate?: boolean
  notes?: boolean
  totalCost?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
}, ExtArgs["result"]["procurement"]>

export type ProcurementSelectScalar = {
  id?: boolean
  poNumber?: boolean
  supplierId?: boolean
  status?: boolean
  orderDate?: boolean
  receivedDate?: boolean
  notes?: boolean
  totalCost?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ProcurementOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "poNumber" | "supplierId" | "status" | "orderDate" | "receivedDate" | "notes" | "totalCost" | "createdAt" | "updatedAt", ExtArgs["result"]["procurement"]>
export type ProcurementInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
  items?: boolean | Prisma.Procurement$itemsArgs<ExtArgs>
  _count?: boolean | Prisma.ProcurementCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProcurementIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
}
export type ProcurementIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  supplier?: boolean | Prisma.SupplierDefaultArgs<ExtArgs>
}

export type $ProcurementPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Procurement"
  objects: {
    supplier: Prisma.$SupplierPayload<ExtArgs>
    items: Prisma.$ProcurementItemPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    poNumber: string
    supplierId: string
    status: $Enums.ProcurementStatus
    orderDate: Date
    receivedDate: Date | null
    notes: string | null
    totalCost: runtime.Decimal
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["procurement"]>
  composites: {}
}

export type ProcurementGetPayload<S extends boolean | null | undefined | ProcurementDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProcurementPayload, S>

export type ProcurementCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProcurementFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProcurementCountAggregateInputType | true
  }

export interface ProcurementDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Procurement'], meta: { name: 'Procurement' } }
  /**
   * Find zero or one Procurement that matches the filter.
   * @param {ProcurementFindUniqueArgs} args - Arguments to find a Procurement
   * @example
   * // Get one Procurement
   * const procurement = await prisma.procurement.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProcurementFindUniqueArgs>(args: Prisma.SelectSubset<T, ProcurementFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProcurementClient<runtime.Types.Result.GetResult<Prisma.$ProcurementPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Procurement that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProcurementFindUniqueOrThrowArgs} args - Arguments to find a Procurement
   * @example
   * // Get one Procurement
   * const procurement = await prisma.procurement.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProcurementFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProcurementFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProcurementClient<runtime.Types.Result.GetResult<Prisma.$ProcurementPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Procurement that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProcurementFindFirstArgs} args - Arguments to find a Procurement
   * @example
   * // Get one Procurement
   * const procurement = await prisma.procurement.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProcurementFindFirstArgs>(args?: Prisma.SelectSubset<T, ProcurementFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProcurementClient<runtime.Types.Result.GetResult<Prisma.$ProcurementPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Procurement that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProcurementFindFirstOrThrowArgs} args - Arguments to find a Procurement
   * @example
   * // Get one Procurement
   * const procurement = await prisma.procurement.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProcurementFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProcurementFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProcurementClient<runtime.Types.Result.GetResult<Prisma.$ProcurementPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Procurements that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProcurementFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Procurements
   * const procurements = await prisma.procurement.findMany()
   * 
   * // Get first 10 Procurements
   * const procurements = await prisma.procurement.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const procurementWithIdOnly = await prisma.procurement.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProcurementFindManyArgs>(args?: Prisma.SelectSubset<T, ProcurementFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProcurementPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Procurement.
   * @param {ProcurementCreateArgs} args - Arguments to create a Procurement.
   * @example
   * // Create one Procurement
   * const Procurement = await prisma.procurement.create({
   *   data: {
   *     // ... data to create a Procurement
   *   }
   * })
   * 
   */
  create<T extends ProcurementCreateArgs>(args: Prisma.SelectSubset<T, ProcurementCreateArgs<ExtArgs>>): Prisma.Prisma__ProcurementClient<runtime.Types.Result.GetResult<Prisma.$ProcurementPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Procurements.
   * @param {ProcurementCreateManyArgs} args - Arguments to create many Procurements.
   * @example
   * // Create many Procurements
   * const procurement = await prisma.procurement.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProcurementCreateManyArgs>(args?: Prisma.SelectSubset<T, ProcurementCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Procurements and returns the data saved in the database.
   * @param {ProcurementCreateManyAndReturnArgs} args - Arguments to create many Procurements.
   * @example
   * // Create many Procurements
   * const procurement = await prisma.procurement.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Procurements and only return the `id`
   * const procurementWithIdOnly = await prisma.procurement.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProcurementCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProcurementCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProcurementPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Procurement.
   * @param {ProcurementDeleteArgs} args - Arguments to delete one Procurement.
   * @example
   * // Delete one Procurement
   * const Procurement = await prisma.procurement.delete({
   *   where: {
   *     // ... filter to delete one Procurement
   *   }
   * })
   * 
   */
  delete<T extends ProcurementDeleteArgs>(args: Prisma.SelectSubset<T, ProcurementDeleteArgs<ExtArgs>>): Prisma.Prisma__ProcurementClient<runtime.Types.Result.GetResult<Prisma.$ProcurementPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Procurement.
   * @param {ProcurementUpdateArgs} args - Arguments to update one Procurement.
   * @example
   * // Update one Procurement
   * const procurement = await prisma.procurement.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProcurementUpdateArgs>(args: Prisma.SelectSubset<T, ProcurementUpdateArgs<ExtArgs>>): Prisma.Prisma__ProcurementClient<runtime.Types.Result.GetResult<Prisma.$ProcurementPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Procurements.
   * @param {ProcurementDeleteManyArgs} args - Arguments to filter Procurements to delete.
   * @example
   * // Delete a few Procurements
   * const { count } = await prisma.procurement.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProcurementDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProcurementDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Procurements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProcurementUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Procurements
   * const procurement = await prisma.procurement.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProcurementUpdateManyArgs>(args: Prisma.SelectSubset<T, ProcurementUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Procurements and returns the data updated in the database.
   * @param {ProcurementUpdateManyAndReturnArgs} args - Arguments to update many Procurements.
   * @example
   * // Update many Procurements
   * const procurement = await prisma.procurement.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Procurements and only return the `id`
   * const procurementWithIdOnly = await prisma.procurement.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProcurementUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProcurementUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProcurementPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Procurement.
   * @param {ProcurementUpsertArgs} args - Arguments to update or create a Procurement.
   * @example
   * // Update or create a Procurement
   * const procurement = await prisma.procurement.upsert({
   *   create: {
   *     // ... data to create a Procurement
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Procurement we want to update
   *   }
   * })
   */
  upsert<T extends ProcurementUpsertArgs>(args: Prisma.SelectSubset<T, ProcurementUpsertArgs<ExtArgs>>): Prisma.Prisma__ProcurementClient<runtime.Types.Result.GetResult<Prisma.$ProcurementPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Procurements.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProcurementCountArgs} args - Arguments to filter Procurements to count.
   * @example
   * // Count the number of Procurements
   * const count = await prisma.procurement.count({
   *   where: {
   *     // ... the filter for the Procurements we want to count
   *   }
   * })
  **/
  count<T extends ProcurementCountArgs>(
    args?: Prisma.Subset<T, ProcurementCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProcurementCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Procurement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProcurementAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProcurementAggregateArgs>(args: Prisma.Subset<T, ProcurementAggregateArgs>): Prisma.PrismaPromise<GetProcurementAggregateType<T>>

  /**
   * Group by Procurement.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProcurementGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProcurementGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProcurementGroupByArgs['orderBy'] }
      : { orderBy?: ProcurementGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProcurementGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProcurementGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Procurement model
 */
readonly fields: ProcurementFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Procurement.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProcurementClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  supplier<T extends Prisma.SupplierDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SupplierDefaultArgs<ExtArgs>>): Prisma.Prisma__SupplierClient<runtime.Types.Result.GetResult<Prisma.$SupplierPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  items<T extends Prisma.Procurement$itemsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Procurement$itemsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProcurementItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Procurement model
 */
export interface ProcurementFieldRefs {
  readonly id: Prisma.FieldRef<"Procurement", 'String'>
  readonly poNumber: Prisma.FieldRef<"Procurement", 'String'>
  readonly supplierId: Prisma.FieldRef<"Procurement", 'String'>
  readonly status: Prisma.FieldRef<"Procurement", 'ProcurementStatus'>
  readonly orderDate: Prisma.FieldRef<"Procurement", 'DateTime'>
  readonly receivedDate: Prisma.FieldRef<"Procurement", 'DateTime'>
  readonly notes: Prisma.FieldRef<"Procurement", 'String'>
  readonly totalCost: Prisma.FieldRef<"Procurement", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"Procurement", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Procurement", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Procurement findUnique
 */
export type ProcurementFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Procurement
   */
  select?: Prisma.ProcurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Procurement
   */
  omit?: Prisma.ProcurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProcurementInclude<ExtArgs> | null
  /**
   * Filter, which Procurement to fetch.
   */
  where: Prisma.ProcurementWhereUniqueInput
}

/**
 * Procurement findUniqueOrThrow
 */
export type ProcurementFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Procurement
   */
  select?: Prisma.ProcurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Procurement
   */
  omit?: Prisma.ProcurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProcurementInclude<ExtArgs> | null
  /**
   * Filter, which Procurement to fetch.
   */
  where: Prisma.ProcurementWhereUniqueInput
}

/**
 * Procurement findFirst
 */
export type ProcurementFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Procurement
   */
  select?: Prisma.ProcurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Procurement
   */
  omit?: Prisma.ProcurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProcurementInclude<ExtArgs> | null
  /**
   * Filter, which Procurement to fetch.
   */
  where?: Prisma.ProcurementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Procurements to fetch.
   */
  orderBy?: Prisma.ProcurementOrderByWithRelationInput | Prisma.ProcurementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Procurements.
   */
  cursor?: Prisma.ProcurementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Procurements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Procurements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Procurements.
   */
  distinct?: Prisma.ProcurementScalarFieldEnum | Prisma.ProcurementScalarFieldEnum[]
}

/**
 * Procurement findFirstOrThrow
 */
export type ProcurementFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Procurement
   */
  select?: Prisma.ProcurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Procurement
   */
  omit?: Prisma.ProcurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProcurementInclude<ExtArgs> | null
  /**
   * Filter, which Procurement to fetch.
   */
  where?: Prisma.ProcurementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Procurements to fetch.
   */
  orderBy?: Prisma.ProcurementOrderByWithRelationInput | Prisma.ProcurementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Procurements.
   */
  cursor?: Prisma.ProcurementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Procurements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Procurements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Procurements.
   */
  distinct?: Prisma.ProcurementScalarFieldEnum | Prisma.ProcurementScalarFieldEnum[]
}

/**
 * Procurement findMany
 */
export type ProcurementFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Procurement
   */
  select?: Prisma.ProcurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Procurement
   */
  omit?: Prisma.ProcurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProcurementInclude<ExtArgs> | null
  /**
   * Filter, which Procurements to fetch.
   */
  where?: Prisma.ProcurementWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Procurements to fetch.
   */
  orderBy?: Prisma.ProcurementOrderByWithRelationInput | Prisma.ProcurementOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Procurements.
   */
  cursor?: Prisma.ProcurementWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Procurements from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Procurements.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Procurements.
   */
  distinct?: Prisma.ProcurementScalarFieldEnum | Prisma.ProcurementScalarFieldEnum[]
}

/**
 * Procurement create
 */
export type ProcurementCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Procurement
   */
  select?: Prisma.ProcurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Procurement
   */
  omit?: Prisma.ProcurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProcurementInclude<ExtArgs> | null
  /**
   * The data needed to create a Procurement.
   */
  data: Prisma.XOR<Prisma.ProcurementCreateInput, Prisma.ProcurementUncheckedCreateInput>
}

/**
 * Procurement createMany
 */
export type ProcurementCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Procurements.
   */
  data: Prisma.ProcurementCreateManyInput | Prisma.ProcurementCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Procurement createManyAndReturn
 */
export type ProcurementCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Procurement
   */
  select?: Prisma.ProcurementSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Procurement
   */
  omit?: Prisma.ProcurementOmit<ExtArgs> | null
  /**
   * The data used to create many Procurements.
   */
  data: Prisma.ProcurementCreateManyInput | Prisma.ProcurementCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProcurementIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Procurement update
 */
export type ProcurementUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Procurement
   */
  select?: Prisma.ProcurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Procurement
   */
  omit?: Prisma.ProcurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProcurementInclude<ExtArgs> | null
  /**
   * The data needed to update a Procurement.
   */
  data: Prisma.XOR<Prisma.ProcurementUpdateInput, Prisma.ProcurementUncheckedUpdateInput>
  /**
   * Choose, which Procurement to update.
   */
  where: Prisma.ProcurementWhereUniqueInput
}

/**
 * Procurement updateMany
 */
export type ProcurementUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Procurements.
   */
  data: Prisma.XOR<Prisma.ProcurementUpdateManyMutationInput, Prisma.ProcurementUncheckedUpdateManyInput>
  /**
   * Filter which Procurements to update
   */
  where?: Prisma.ProcurementWhereInput
  /**
   * Limit how many Procurements to update.
   */
  limit?: number
}

/**
 * Procurement updateManyAndReturn
 */
export type ProcurementUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Procurement
   */
  select?: Prisma.ProcurementSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Procurement
   */
  omit?: Prisma.ProcurementOmit<ExtArgs> | null
  /**
   * The data used to update Procurements.
   */
  data: Prisma.XOR<Prisma.ProcurementUpdateManyMutationInput, Prisma.ProcurementUncheckedUpdateManyInput>
  /**
   * Filter which Procurements to update
   */
  where?: Prisma.ProcurementWhereInput
  /**
   * Limit how many Procurements to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProcurementIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Procurement upsert
 */
export type ProcurementUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Procurement
   */
  select?: Prisma.ProcurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Procurement
   */
  omit?: Prisma.ProcurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProcurementInclude<ExtArgs> | null
  /**
   * The filter to search for the Procurement to update in case it exists.
   */
  where: Prisma.ProcurementWhereUniqueInput
  /**
   * In case the Procurement found by the `where` argument doesn't exist, create a new Procurement with this data.
   */
  create: Prisma.XOR<Prisma.ProcurementCreateInput, Prisma.ProcurementUncheckedCreateInput>
  /**
   * In case the Procurement was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProcurementUpdateInput, Prisma.ProcurementUncheckedUpdateInput>
}

/**
 * Procurement delete
 */
export type ProcurementDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Procurement
   */
  select?: Prisma.ProcurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Procurement
   */
  omit?: Prisma.ProcurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProcurementInclude<ExtArgs> | null
  /**
   * Filter which Procurement to delete.
   */
  where: Prisma.ProcurementWhereUniqueInput
}

/**
 * Procurement deleteMany
 */
export type ProcurementDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Procurements to delete
   */
  where?: Prisma.ProcurementWhereInput
  /**
   * Limit how many Procurements to delete.
   */
  limit?: number
}

/**
 * Procurement.items
 */
export type Procurement$itemsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProcurementItem
   */
  select?: Prisma.ProcurementItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProcurementItem
   */
  omit?: Prisma.ProcurementItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProcurementItemInclude<ExtArgs> | null
  where?: Prisma.ProcurementItemWhereInput
  orderBy?: Prisma.ProcurementItemOrderByWithRelationInput | Prisma.ProcurementItemOrderByWithRelationInput[]
  cursor?: Prisma.ProcurementItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProcurementItemScalarFieldEnum | Prisma.ProcurementItemScalarFieldEnum[]
}

/**
 * Procurement without action
 */
export type ProcurementDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Procurement
   */
  select?: Prisma.ProcurementSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Procurement
   */
  omit?: Prisma.ProcurementOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProcurementInclude<ExtArgs> | null
}
