
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `StockAudit` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model StockAudit
 * 
 */
export type StockAuditModel = runtime.Types.Result.DefaultSelection<Prisma.$StockAuditPayload>

export type AggregateStockAudit = {
  _count: StockAuditCountAggregateOutputType | null
  _avg: StockAuditAvgAggregateOutputType | null
  _sum: StockAuditSumAggregateOutputType | null
  _min: StockAuditMinAggregateOutputType | null
  _max: StockAuditMaxAggregateOutputType | null
}

export type StockAuditAvgAggregateOutputType = {
  expectedQty: number | null
  actualQty: number | null
  variance: number | null
}

export type StockAuditSumAggregateOutputType = {
  expectedQty: number | null
  actualQty: number | null
  variance: number | null
}

export type StockAuditMinAggregateOutputType = {
  id: string | null
  variantId: string | null
  expectedQty: number | null
  actualQty: number | null
  variance: number | null
  notes: string | null
  conductedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StockAuditMaxAggregateOutputType = {
  id: string | null
  variantId: string | null
  expectedQty: number | null
  actualQty: number | null
  variance: number | null
  notes: string | null
  conductedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type StockAuditCountAggregateOutputType = {
  id: number
  variantId: number
  expectedQty: number
  actualQty: number
  variance: number
  notes: number
  conductedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type StockAuditAvgAggregateInputType = {
  expectedQty?: true
  actualQty?: true
  variance?: true
}

export type StockAuditSumAggregateInputType = {
  expectedQty?: true
  actualQty?: true
  variance?: true
}

export type StockAuditMinAggregateInputType = {
  id?: true
  variantId?: true
  expectedQty?: true
  actualQty?: true
  variance?: true
  notes?: true
  conductedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type StockAuditMaxAggregateInputType = {
  id?: true
  variantId?: true
  expectedQty?: true
  actualQty?: true
  variance?: true
  notes?: true
  conductedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type StockAuditCountAggregateInputType = {
  id?: true
  variantId?: true
  expectedQty?: true
  actualQty?: true
  variance?: true
  notes?: true
  conductedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type StockAuditAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StockAudit to aggregate.
   */
  where?: Prisma.StockAuditWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StockAudits to fetch.
   */
  orderBy?: Prisma.StockAuditOrderByWithRelationInput | Prisma.StockAuditOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.StockAuditWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StockAudits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StockAudits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned StockAudits
  **/
  _count?: true | StockAuditCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: StockAuditAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: StockAuditSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: StockAuditMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: StockAuditMaxAggregateInputType
}

export type GetStockAuditAggregateType<T extends StockAuditAggregateArgs> = {
      [P in keyof T & keyof AggregateStockAudit]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateStockAudit[P]>
    : Prisma.GetScalarType<T[P], AggregateStockAudit[P]>
}




export type StockAuditGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.StockAuditWhereInput
  orderBy?: Prisma.StockAuditOrderByWithAggregationInput | Prisma.StockAuditOrderByWithAggregationInput[]
  by: Prisma.StockAuditScalarFieldEnum[] | Prisma.StockAuditScalarFieldEnum
  having?: Prisma.StockAuditScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: StockAuditCountAggregateInputType | true
  _avg?: StockAuditAvgAggregateInputType
  _sum?: StockAuditSumAggregateInputType
  _min?: StockAuditMinAggregateInputType
  _max?: StockAuditMaxAggregateInputType
}

export type StockAuditGroupByOutputType = {
  id: string
  variantId: string
  expectedQty: number
  actualQty: number
  variance: number
  notes: string | null
  conductedAt: Date
  createdAt: Date
  updatedAt: Date
  _count: StockAuditCountAggregateOutputType | null
  _avg: StockAuditAvgAggregateOutputType | null
  _sum: StockAuditSumAggregateOutputType | null
  _min: StockAuditMinAggregateOutputType | null
  _max: StockAuditMaxAggregateOutputType | null
}

export type GetStockAuditGroupByPayload<T extends StockAuditGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<StockAuditGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof StockAuditGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], StockAuditGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], StockAuditGroupByOutputType[P]>
      }
    >
  >



export type StockAuditWhereInput = {
  AND?: Prisma.StockAuditWhereInput | Prisma.StockAuditWhereInput[]
  OR?: Prisma.StockAuditWhereInput[]
  NOT?: Prisma.StockAuditWhereInput | Prisma.StockAuditWhereInput[]
  id?: Prisma.StringFilter<"StockAudit"> | string
  variantId?: Prisma.StringFilter<"StockAudit"> | string
  expectedQty?: Prisma.IntFilter<"StockAudit"> | number
  actualQty?: Prisma.IntFilter<"StockAudit"> | number
  variance?: Prisma.IntFilter<"StockAudit"> | number
  notes?: Prisma.StringNullableFilter<"StockAudit"> | string | null
  conductedAt?: Prisma.DateTimeFilter<"StockAudit"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"StockAudit"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StockAudit"> | Date | string
  variant?: Prisma.XOR<Prisma.ProductVariantScalarRelationFilter, Prisma.ProductVariantWhereInput>
}

export type StockAuditOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  expectedQty?: Prisma.SortOrder
  actualQty?: Prisma.SortOrder
  variance?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  conductedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  variant?: Prisma.ProductVariantOrderByWithRelationInput
}

export type StockAuditWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.StockAuditWhereInput | Prisma.StockAuditWhereInput[]
  OR?: Prisma.StockAuditWhereInput[]
  NOT?: Prisma.StockAuditWhereInput | Prisma.StockAuditWhereInput[]
  variantId?: Prisma.StringFilter<"StockAudit"> | string
  expectedQty?: Prisma.IntFilter<"StockAudit"> | number
  actualQty?: Prisma.IntFilter<"StockAudit"> | number
  variance?: Prisma.IntFilter<"StockAudit"> | number
  notes?: Prisma.StringNullableFilter<"StockAudit"> | string | null
  conductedAt?: Prisma.DateTimeFilter<"StockAudit"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"StockAudit"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StockAudit"> | Date | string
  variant?: Prisma.XOR<Prisma.ProductVariantScalarRelationFilter, Prisma.ProductVariantWhereInput>
}, "id">

export type StockAuditOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  expectedQty?: Prisma.SortOrder
  actualQty?: Prisma.SortOrder
  variance?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  conductedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.StockAuditCountOrderByAggregateInput
  _avg?: Prisma.StockAuditAvgOrderByAggregateInput
  _max?: Prisma.StockAuditMaxOrderByAggregateInput
  _min?: Prisma.StockAuditMinOrderByAggregateInput
  _sum?: Prisma.StockAuditSumOrderByAggregateInput
}

export type StockAuditScalarWhereWithAggregatesInput = {
  AND?: Prisma.StockAuditScalarWhereWithAggregatesInput | Prisma.StockAuditScalarWhereWithAggregatesInput[]
  OR?: Prisma.StockAuditScalarWhereWithAggregatesInput[]
  NOT?: Prisma.StockAuditScalarWhereWithAggregatesInput | Prisma.StockAuditScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"StockAudit"> | string
  variantId?: Prisma.StringWithAggregatesFilter<"StockAudit"> | string
  expectedQty?: Prisma.IntWithAggregatesFilter<"StockAudit"> | number
  actualQty?: Prisma.IntWithAggregatesFilter<"StockAudit"> | number
  variance?: Prisma.IntWithAggregatesFilter<"StockAudit"> | number
  notes?: Prisma.StringNullableWithAggregatesFilter<"StockAudit"> | string | null
  conductedAt?: Prisma.DateTimeWithAggregatesFilter<"StockAudit"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"StockAudit"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"StockAudit"> | Date | string
}

export type StockAuditCreateInput = {
  id?: string
  expectedQty: number
  actualQty: number
  variance: number
  notes?: string | null
  conductedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  variant: Prisma.ProductVariantCreateNestedOneWithoutStockAuditsInput
}

export type StockAuditUncheckedCreateInput = {
  id?: string
  variantId: string
  expectedQty: number
  actualQty: number
  variance: number
  notes?: string | null
  conductedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StockAuditUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQty?: Prisma.IntFieldUpdateOperationsInput | number
  actualQty?: Prisma.IntFieldUpdateOperationsInput | number
  variance?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conductedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  variant?: Prisma.ProductVariantUpdateOneRequiredWithoutStockAuditsNestedInput
}

export type StockAuditUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQty?: Prisma.IntFieldUpdateOperationsInput | number
  actualQty?: Prisma.IntFieldUpdateOperationsInput | number
  variance?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conductedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockAuditCreateManyInput = {
  id?: string
  variantId: string
  expectedQty: number
  actualQty: number
  variance: number
  notes?: string | null
  conductedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StockAuditUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQty?: Prisma.IntFieldUpdateOperationsInput | number
  actualQty?: Prisma.IntFieldUpdateOperationsInput | number
  variance?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conductedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockAuditUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  variantId?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQty?: Prisma.IntFieldUpdateOperationsInput | number
  actualQty?: Prisma.IntFieldUpdateOperationsInput | number
  variance?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conductedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockAuditListRelationFilter = {
  every?: Prisma.StockAuditWhereInput
  some?: Prisma.StockAuditWhereInput
  none?: Prisma.StockAuditWhereInput
}

export type StockAuditOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StockAuditCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  expectedQty?: Prisma.SortOrder
  actualQty?: Prisma.SortOrder
  variance?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  conductedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StockAuditAvgOrderByAggregateInput = {
  expectedQty?: Prisma.SortOrder
  actualQty?: Prisma.SortOrder
  variance?: Prisma.SortOrder
}

export type StockAuditMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  expectedQty?: Prisma.SortOrder
  actualQty?: Prisma.SortOrder
  variance?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  conductedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StockAuditMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  variantId?: Prisma.SortOrder
  expectedQty?: Prisma.SortOrder
  actualQty?: Prisma.SortOrder
  variance?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  conductedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type StockAuditSumOrderByAggregateInput = {
  expectedQty?: Prisma.SortOrder
  actualQty?: Prisma.SortOrder
  variance?: Prisma.SortOrder
}

export type StockAuditCreateNestedManyWithoutVariantInput = {
  create?: Prisma.XOR<Prisma.StockAuditCreateWithoutVariantInput, Prisma.StockAuditUncheckedCreateWithoutVariantInput> | Prisma.StockAuditCreateWithoutVariantInput[] | Prisma.StockAuditUncheckedCreateWithoutVariantInput[]
  connectOrCreate?: Prisma.StockAuditCreateOrConnectWithoutVariantInput | Prisma.StockAuditCreateOrConnectWithoutVariantInput[]
  createMany?: Prisma.StockAuditCreateManyVariantInputEnvelope
  connect?: Prisma.StockAuditWhereUniqueInput | Prisma.StockAuditWhereUniqueInput[]
}

export type StockAuditUncheckedCreateNestedManyWithoutVariantInput = {
  create?: Prisma.XOR<Prisma.StockAuditCreateWithoutVariantInput, Prisma.StockAuditUncheckedCreateWithoutVariantInput> | Prisma.StockAuditCreateWithoutVariantInput[] | Prisma.StockAuditUncheckedCreateWithoutVariantInput[]
  connectOrCreate?: Prisma.StockAuditCreateOrConnectWithoutVariantInput | Prisma.StockAuditCreateOrConnectWithoutVariantInput[]
  createMany?: Prisma.StockAuditCreateManyVariantInputEnvelope
  connect?: Prisma.StockAuditWhereUniqueInput | Prisma.StockAuditWhereUniqueInput[]
}

export type StockAuditUpdateManyWithoutVariantNestedInput = {
  create?: Prisma.XOR<Prisma.StockAuditCreateWithoutVariantInput, Prisma.StockAuditUncheckedCreateWithoutVariantInput> | Prisma.StockAuditCreateWithoutVariantInput[] | Prisma.StockAuditUncheckedCreateWithoutVariantInput[]
  connectOrCreate?: Prisma.StockAuditCreateOrConnectWithoutVariantInput | Prisma.StockAuditCreateOrConnectWithoutVariantInput[]
  upsert?: Prisma.StockAuditUpsertWithWhereUniqueWithoutVariantInput | Prisma.StockAuditUpsertWithWhereUniqueWithoutVariantInput[]
  createMany?: Prisma.StockAuditCreateManyVariantInputEnvelope
  set?: Prisma.StockAuditWhereUniqueInput | Prisma.StockAuditWhereUniqueInput[]
  disconnect?: Prisma.StockAuditWhereUniqueInput | Prisma.StockAuditWhereUniqueInput[]
  delete?: Prisma.StockAuditWhereUniqueInput | Prisma.StockAuditWhereUniqueInput[]
  connect?: Prisma.StockAuditWhereUniqueInput | Prisma.StockAuditWhereUniqueInput[]
  update?: Prisma.StockAuditUpdateWithWhereUniqueWithoutVariantInput | Prisma.StockAuditUpdateWithWhereUniqueWithoutVariantInput[]
  updateMany?: Prisma.StockAuditUpdateManyWithWhereWithoutVariantInput | Prisma.StockAuditUpdateManyWithWhereWithoutVariantInput[]
  deleteMany?: Prisma.StockAuditScalarWhereInput | Prisma.StockAuditScalarWhereInput[]
}

export type StockAuditUncheckedUpdateManyWithoutVariantNestedInput = {
  create?: Prisma.XOR<Prisma.StockAuditCreateWithoutVariantInput, Prisma.StockAuditUncheckedCreateWithoutVariantInput> | Prisma.StockAuditCreateWithoutVariantInput[] | Prisma.StockAuditUncheckedCreateWithoutVariantInput[]
  connectOrCreate?: Prisma.StockAuditCreateOrConnectWithoutVariantInput | Prisma.StockAuditCreateOrConnectWithoutVariantInput[]
  upsert?: Prisma.StockAuditUpsertWithWhereUniqueWithoutVariantInput | Prisma.StockAuditUpsertWithWhereUniqueWithoutVariantInput[]
  createMany?: Prisma.StockAuditCreateManyVariantInputEnvelope
  set?: Prisma.StockAuditWhereUniqueInput | Prisma.StockAuditWhereUniqueInput[]
  disconnect?: Prisma.StockAuditWhereUniqueInput | Prisma.StockAuditWhereUniqueInput[]
  delete?: Prisma.StockAuditWhereUniqueInput | Prisma.StockAuditWhereUniqueInput[]
  connect?: Prisma.StockAuditWhereUniqueInput | Prisma.StockAuditWhereUniqueInput[]
  update?: Prisma.StockAuditUpdateWithWhereUniqueWithoutVariantInput | Prisma.StockAuditUpdateWithWhereUniqueWithoutVariantInput[]
  updateMany?: Prisma.StockAuditUpdateManyWithWhereWithoutVariantInput | Prisma.StockAuditUpdateManyWithWhereWithoutVariantInput[]
  deleteMany?: Prisma.StockAuditScalarWhereInput | Prisma.StockAuditScalarWhereInput[]
}

export type StockAuditCreateWithoutVariantInput = {
  id?: string
  expectedQty: number
  actualQty: number
  variance: number
  notes?: string | null
  conductedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StockAuditUncheckedCreateWithoutVariantInput = {
  id?: string
  expectedQty: number
  actualQty: number
  variance: number
  notes?: string | null
  conductedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StockAuditCreateOrConnectWithoutVariantInput = {
  where: Prisma.StockAuditWhereUniqueInput
  create: Prisma.XOR<Prisma.StockAuditCreateWithoutVariantInput, Prisma.StockAuditUncheckedCreateWithoutVariantInput>
}

export type StockAuditCreateManyVariantInputEnvelope = {
  data: Prisma.StockAuditCreateManyVariantInput | Prisma.StockAuditCreateManyVariantInput[]
  skipDuplicates?: boolean
}

export type StockAuditUpsertWithWhereUniqueWithoutVariantInput = {
  where: Prisma.StockAuditWhereUniqueInput
  update: Prisma.XOR<Prisma.StockAuditUpdateWithoutVariantInput, Prisma.StockAuditUncheckedUpdateWithoutVariantInput>
  create: Prisma.XOR<Prisma.StockAuditCreateWithoutVariantInput, Prisma.StockAuditUncheckedCreateWithoutVariantInput>
}

export type StockAuditUpdateWithWhereUniqueWithoutVariantInput = {
  where: Prisma.StockAuditWhereUniqueInput
  data: Prisma.XOR<Prisma.StockAuditUpdateWithoutVariantInput, Prisma.StockAuditUncheckedUpdateWithoutVariantInput>
}

export type StockAuditUpdateManyWithWhereWithoutVariantInput = {
  where: Prisma.StockAuditScalarWhereInput
  data: Prisma.XOR<Prisma.StockAuditUpdateManyMutationInput, Prisma.StockAuditUncheckedUpdateManyWithoutVariantInput>
}

export type StockAuditScalarWhereInput = {
  AND?: Prisma.StockAuditScalarWhereInput | Prisma.StockAuditScalarWhereInput[]
  OR?: Prisma.StockAuditScalarWhereInput[]
  NOT?: Prisma.StockAuditScalarWhereInput | Prisma.StockAuditScalarWhereInput[]
  id?: Prisma.StringFilter<"StockAudit"> | string
  variantId?: Prisma.StringFilter<"StockAudit"> | string
  expectedQty?: Prisma.IntFilter<"StockAudit"> | number
  actualQty?: Prisma.IntFilter<"StockAudit"> | number
  variance?: Prisma.IntFilter<"StockAudit"> | number
  notes?: Prisma.StringNullableFilter<"StockAudit"> | string | null
  conductedAt?: Prisma.DateTimeFilter<"StockAudit"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"StockAudit"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"StockAudit"> | Date | string
}

export type StockAuditCreateManyVariantInput = {
  id?: string
  expectedQty: number
  actualQty: number
  variance: number
  notes?: string | null
  conductedAt?: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type StockAuditUpdateWithoutVariantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQty?: Prisma.IntFieldUpdateOperationsInput | number
  actualQty?: Prisma.IntFieldUpdateOperationsInput | number
  variance?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conductedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockAuditUncheckedUpdateWithoutVariantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQty?: Prisma.IntFieldUpdateOperationsInput | number
  actualQty?: Prisma.IntFieldUpdateOperationsInput | number
  variance?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conductedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type StockAuditUncheckedUpdateManyWithoutVariantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  expectedQty?: Prisma.IntFieldUpdateOperationsInput | number
  actualQty?: Prisma.IntFieldUpdateOperationsInput | number
  variance?: Prisma.IntFieldUpdateOperationsInput | number
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conductedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type StockAuditSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  variantId?: boolean
  expectedQty?: boolean
  actualQty?: boolean
  variance?: boolean
  notes?: boolean
  conductedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["stockAudit"]>

export type StockAuditSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  variantId?: boolean
  expectedQty?: boolean
  actualQty?: boolean
  variance?: boolean
  notes?: boolean
  conductedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["stockAudit"]>

export type StockAuditSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  variantId?: boolean
  expectedQty?: boolean
  actualQty?: boolean
  variance?: boolean
  notes?: boolean
  conductedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["stockAudit"]>

export type StockAuditSelectScalar = {
  id?: boolean
  variantId?: boolean
  expectedQty?: boolean
  actualQty?: boolean
  variance?: boolean
  notes?: boolean
  conductedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type StockAuditOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "variantId" | "expectedQty" | "actualQty" | "variance" | "notes" | "conductedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["stockAudit"]>
export type StockAuditInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
}
export type StockAuditIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
}
export type StockAuditIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  variant?: boolean | Prisma.ProductVariantDefaultArgs<ExtArgs>
}

export type $StockAuditPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "StockAudit"
  objects: {
    variant: Prisma.$ProductVariantPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    variantId: string
    expectedQty: number
    actualQty: number
    variance: number
    notes: string | null
    conductedAt: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["stockAudit"]>
  composites: {}
}

export type StockAuditGetPayload<S extends boolean | null | undefined | StockAuditDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$StockAuditPayload, S>

export type StockAuditCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<StockAuditFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: StockAuditCountAggregateInputType | true
  }

export interface StockAuditDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['StockAudit'], meta: { name: 'StockAudit' } }
  /**
   * Find zero or one StockAudit that matches the filter.
   * @param {StockAuditFindUniqueArgs} args - Arguments to find a StockAudit
   * @example
   * // Get one StockAudit
   * const stockAudit = await prisma.stockAudit.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends StockAuditFindUniqueArgs>(args: Prisma.SelectSubset<T, StockAuditFindUniqueArgs<ExtArgs>>): Prisma.Prisma__StockAuditClient<runtime.Types.Result.GetResult<Prisma.$StockAuditPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one StockAudit that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {StockAuditFindUniqueOrThrowArgs} args - Arguments to find a StockAudit
   * @example
   * // Get one StockAudit
   * const stockAudit = await prisma.stockAudit.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends StockAuditFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, StockAuditFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__StockAuditClient<runtime.Types.Result.GetResult<Prisma.$StockAuditPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StockAudit that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockAuditFindFirstArgs} args - Arguments to find a StockAudit
   * @example
   * // Get one StockAudit
   * const stockAudit = await prisma.stockAudit.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends StockAuditFindFirstArgs>(args?: Prisma.SelectSubset<T, StockAuditFindFirstArgs<ExtArgs>>): Prisma.Prisma__StockAuditClient<runtime.Types.Result.GetResult<Prisma.$StockAuditPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first StockAudit that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockAuditFindFirstOrThrowArgs} args - Arguments to find a StockAudit
   * @example
   * // Get one StockAudit
   * const stockAudit = await prisma.stockAudit.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends StockAuditFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, StockAuditFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__StockAuditClient<runtime.Types.Result.GetResult<Prisma.$StockAuditPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more StockAudits that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockAuditFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all StockAudits
   * const stockAudits = await prisma.stockAudit.findMany()
   * 
   * // Get first 10 StockAudits
   * const stockAudits = await prisma.stockAudit.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const stockAuditWithIdOnly = await prisma.stockAudit.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends StockAuditFindManyArgs>(args?: Prisma.SelectSubset<T, StockAuditFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StockAuditPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a StockAudit.
   * @param {StockAuditCreateArgs} args - Arguments to create a StockAudit.
   * @example
   * // Create one StockAudit
   * const StockAudit = await prisma.stockAudit.create({
   *   data: {
   *     // ... data to create a StockAudit
   *   }
   * })
   * 
   */
  create<T extends StockAuditCreateArgs>(args: Prisma.SelectSubset<T, StockAuditCreateArgs<ExtArgs>>): Prisma.Prisma__StockAuditClient<runtime.Types.Result.GetResult<Prisma.$StockAuditPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many StockAudits.
   * @param {StockAuditCreateManyArgs} args - Arguments to create many StockAudits.
   * @example
   * // Create many StockAudits
   * const stockAudit = await prisma.stockAudit.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends StockAuditCreateManyArgs>(args?: Prisma.SelectSubset<T, StockAuditCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many StockAudits and returns the data saved in the database.
   * @param {StockAuditCreateManyAndReturnArgs} args - Arguments to create many StockAudits.
   * @example
   * // Create many StockAudits
   * const stockAudit = await prisma.stockAudit.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many StockAudits and only return the `id`
   * const stockAuditWithIdOnly = await prisma.stockAudit.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends StockAuditCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, StockAuditCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StockAuditPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a StockAudit.
   * @param {StockAuditDeleteArgs} args - Arguments to delete one StockAudit.
   * @example
   * // Delete one StockAudit
   * const StockAudit = await prisma.stockAudit.delete({
   *   where: {
   *     // ... filter to delete one StockAudit
   *   }
   * })
   * 
   */
  delete<T extends StockAuditDeleteArgs>(args: Prisma.SelectSubset<T, StockAuditDeleteArgs<ExtArgs>>): Prisma.Prisma__StockAuditClient<runtime.Types.Result.GetResult<Prisma.$StockAuditPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one StockAudit.
   * @param {StockAuditUpdateArgs} args - Arguments to update one StockAudit.
   * @example
   * // Update one StockAudit
   * const stockAudit = await prisma.stockAudit.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends StockAuditUpdateArgs>(args: Prisma.SelectSubset<T, StockAuditUpdateArgs<ExtArgs>>): Prisma.Prisma__StockAuditClient<runtime.Types.Result.GetResult<Prisma.$StockAuditPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more StockAudits.
   * @param {StockAuditDeleteManyArgs} args - Arguments to filter StockAudits to delete.
   * @example
   * // Delete a few StockAudits
   * const { count } = await prisma.stockAudit.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends StockAuditDeleteManyArgs>(args?: Prisma.SelectSubset<T, StockAuditDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StockAudits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockAuditUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many StockAudits
   * const stockAudit = await prisma.stockAudit.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends StockAuditUpdateManyArgs>(args: Prisma.SelectSubset<T, StockAuditUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more StockAudits and returns the data updated in the database.
   * @param {StockAuditUpdateManyAndReturnArgs} args - Arguments to update many StockAudits.
   * @example
   * // Update many StockAudits
   * const stockAudit = await prisma.stockAudit.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more StockAudits and only return the `id`
   * const stockAuditWithIdOnly = await prisma.stockAudit.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends StockAuditUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, StockAuditUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$StockAuditPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one StockAudit.
   * @param {StockAuditUpsertArgs} args - Arguments to update or create a StockAudit.
   * @example
   * // Update or create a StockAudit
   * const stockAudit = await prisma.stockAudit.upsert({
   *   create: {
   *     // ... data to create a StockAudit
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the StockAudit we want to update
   *   }
   * })
   */
  upsert<T extends StockAuditUpsertArgs>(args: Prisma.SelectSubset<T, StockAuditUpsertArgs<ExtArgs>>): Prisma.Prisma__StockAuditClient<runtime.Types.Result.GetResult<Prisma.$StockAuditPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of StockAudits.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockAuditCountArgs} args - Arguments to filter StockAudits to count.
   * @example
   * // Count the number of StockAudits
   * const count = await prisma.stockAudit.count({
   *   where: {
   *     // ... the filter for the StockAudits we want to count
   *   }
   * })
  **/
  count<T extends StockAuditCountArgs>(
    args?: Prisma.Subset<T, StockAuditCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], StockAuditCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a StockAudit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockAuditAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends StockAuditAggregateArgs>(args: Prisma.Subset<T, StockAuditAggregateArgs>): Prisma.PrismaPromise<GetStockAuditAggregateType<T>>

  /**
   * Group by StockAudit.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {StockAuditGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends StockAuditGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: StockAuditGroupByArgs['orderBy'] }
      : { orderBy?: StockAuditGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, StockAuditGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetStockAuditGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the StockAudit model
 */
readonly fields: StockAuditFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for StockAudit.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__StockAuditClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  variant<T extends Prisma.ProductVariantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductVariantDefaultArgs<ExtArgs>>): Prisma.Prisma__ProductVariantClient<runtime.Types.Result.GetResult<Prisma.$ProductVariantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the StockAudit model
 */
export interface StockAuditFieldRefs {
  readonly id: Prisma.FieldRef<"StockAudit", 'String'>
  readonly variantId: Prisma.FieldRef<"StockAudit", 'String'>
  readonly expectedQty: Prisma.FieldRef<"StockAudit", 'Int'>
  readonly actualQty: Prisma.FieldRef<"StockAudit", 'Int'>
  readonly variance: Prisma.FieldRef<"StockAudit", 'Int'>
  readonly notes: Prisma.FieldRef<"StockAudit", 'String'>
  readonly conductedAt: Prisma.FieldRef<"StockAudit", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"StockAudit", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"StockAudit", 'DateTime'>
}
    

// Custom InputTypes
/**
 * StockAudit findUnique
 */
export type StockAuditFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockAudit
   */
  select?: Prisma.StockAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockAudit
   */
  omit?: Prisma.StockAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockAuditInclude<ExtArgs> | null
  /**
   * Filter, which StockAudit to fetch.
   */
  where: Prisma.StockAuditWhereUniqueInput
}

/**
 * StockAudit findUniqueOrThrow
 */
export type StockAuditFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockAudit
   */
  select?: Prisma.StockAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockAudit
   */
  omit?: Prisma.StockAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockAuditInclude<ExtArgs> | null
  /**
   * Filter, which StockAudit to fetch.
   */
  where: Prisma.StockAuditWhereUniqueInput
}

/**
 * StockAudit findFirst
 */
export type StockAuditFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockAudit
   */
  select?: Prisma.StockAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockAudit
   */
  omit?: Prisma.StockAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockAuditInclude<ExtArgs> | null
  /**
   * Filter, which StockAudit to fetch.
   */
  where?: Prisma.StockAuditWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StockAudits to fetch.
   */
  orderBy?: Prisma.StockAuditOrderByWithRelationInput | Prisma.StockAuditOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StockAudits.
   */
  cursor?: Prisma.StockAuditWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StockAudits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StockAudits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StockAudits.
   */
  distinct?: Prisma.StockAuditScalarFieldEnum | Prisma.StockAuditScalarFieldEnum[]
}

/**
 * StockAudit findFirstOrThrow
 */
export type StockAuditFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockAudit
   */
  select?: Prisma.StockAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockAudit
   */
  omit?: Prisma.StockAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockAuditInclude<ExtArgs> | null
  /**
   * Filter, which StockAudit to fetch.
   */
  where?: Prisma.StockAuditWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StockAudits to fetch.
   */
  orderBy?: Prisma.StockAuditOrderByWithRelationInput | Prisma.StockAuditOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for StockAudits.
   */
  cursor?: Prisma.StockAuditWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StockAudits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StockAudits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StockAudits.
   */
  distinct?: Prisma.StockAuditScalarFieldEnum | Prisma.StockAuditScalarFieldEnum[]
}

/**
 * StockAudit findMany
 */
export type StockAuditFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockAudit
   */
  select?: Prisma.StockAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockAudit
   */
  omit?: Prisma.StockAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockAuditInclude<ExtArgs> | null
  /**
   * Filter, which StockAudits to fetch.
   */
  where?: Prisma.StockAuditWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of StockAudits to fetch.
   */
  orderBy?: Prisma.StockAuditOrderByWithRelationInput | Prisma.StockAuditOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing StockAudits.
   */
  cursor?: Prisma.StockAuditWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` StockAudits from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` StockAudits.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of StockAudits.
   */
  distinct?: Prisma.StockAuditScalarFieldEnum | Prisma.StockAuditScalarFieldEnum[]
}

/**
 * StockAudit create
 */
export type StockAuditCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockAudit
   */
  select?: Prisma.StockAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockAudit
   */
  omit?: Prisma.StockAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockAuditInclude<ExtArgs> | null
  /**
   * The data needed to create a StockAudit.
   */
  data: Prisma.XOR<Prisma.StockAuditCreateInput, Prisma.StockAuditUncheckedCreateInput>
}

/**
 * StockAudit createMany
 */
export type StockAuditCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many StockAudits.
   */
  data: Prisma.StockAuditCreateManyInput | Prisma.StockAuditCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * StockAudit createManyAndReturn
 */
export type StockAuditCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockAudit
   */
  select?: Prisma.StockAuditSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StockAudit
   */
  omit?: Prisma.StockAuditOmit<ExtArgs> | null
  /**
   * The data used to create many StockAudits.
   */
  data: Prisma.StockAuditCreateManyInput | Prisma.StockAuditCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockAuditIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * StockAudit update
 */
export type StockAuditUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockAudit
   */
  select?: Prisma.StockAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockAudit
   */
  omit?: Prisma.StockAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockAuditInclude<ExtArgs> | null
  /**
   * The data needed to update a StockAudit.
   */
  data: Prisma.XOR<Prisma.StockAuditUpdateInput, Prisma.StockAuditUncheckedUpdateInput>
  /**
   * Choose, which StockAudit to update.
   */
  where: Prisma.StockAuditWhereUniqueInput
}

/**
 * StockAudit updateMany
 */
export type StockAuditUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update StockAudits.
   */
  data: Prisma.XOR<Prisma.StockAuditUpdateManyMutationInput, Prisma.StockAuditUncheckedUpdateManyInput>
  /**
   * Filter which StockAudits to update
   */
  where?: Prisma.StockAuditWhereInput
  /**
   * Limit how many StockAudits to update.
   */
  limit?: number
}

/**
 * StockAudit updateManyAndReturn
 */
export type StockAuditUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockAudit
   */
  select?: Prisma.StockAuditSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the StockAudit
   */
  omit?: Prisma.StockAuditOmit<ExtArgs> | null
  /**
   * The data used to update StockAudits.
   */
  data: Prisma.XOR<Prisma.StockAuditUpdateManyMutationInput, Prisma.StockAuditUncheckedUpdateManyInput>
  /**
   * Filter which StockAudits to update
   */
  where?: Prisma.StockAuditWhereInput
  /**
   * Limit how many StockAudits to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockAuditIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * StockAudit upsert
 */
export type StockAuditUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockAudit
   */
  select?: Prisma.StockAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockAudit
   */
  omit?: Prisma.StockAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockAuditInclude<ExtArgs> | null
  /**
   * The filter to search for the StockAudit to update in case it exists.
   */
  where: Prisma.StockAuditWhereUniqueInput
  /**
   * In case the StockAudit found by the `where` argument doesn't exist, create a new StockAudit with this data.
   */
  create: Prisma.XOR<Prisma.StockAuditCreateInput, Prisma.StockAuditUncheckedCreateInput>
  /**
   * In case the StockAudit was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.StockAuditUpdateInput, Prisma.StockAuditUncheckedUpdateInput>
}

/**
 * StockAudit delete
 */
export type StockAuditDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockAudit
   */
  select?: Prisma.StockAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockAudit
   */
  omit?: Prisma.StockAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockAuditInclude<ExtArgs> | null
  /**
   * Filter which StockAudit to delete.
   */
  where: Prisma.StockAuditWhereUniqueInput
}

/**
 * StockAudit deleteMany
 */
export type StockAuditDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which StockAudits to delete
   */
  where?: Prisma.StockAuditWhereInput
  /**
   * Limit how many StockAudits to delete.
   */
  limit?: number
}

/**
 * StockAudit without action
 */
export type StockAuditDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the StockAudit
   */
  select?: Prisma.StockAuditSelect<ExtArgs> | null
  /**
   * Omit specific fields from the StockAudit
   */
  omit?: Prisma.StockAuditOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StockAuditInclude<ExtArgs> | null
}
